### ISSUE TITLE
[RFC]: 修改约定式路由下Layout的实现方式

### ISSUE THREAD

**Issue by KotoriK** [web-infra-dev/modern.js#2256]
## 现状
目前约定式路由下，全局Layout和部分Layout都是和具体的页面组件一起被包裹在```<Route/>```下面的。由于页面是懒加载的，所以在切换路由时，若对应页面的包尚未加载，就可以看到全屏白屏。
## 期望的效果
路由切换时可以让Layout保持显示，不要出现全屏白屏

### 你期望的 API 是什么样子的？

对API没有更改

**Comment by xuchaobei** [comment]
2.0 版本会支持嵌套路由，可以解决这个问题。预计12月底会发布 2.0 的 beta 版本。

**Comment by chenjiahan** [comment]
目前已经可以在 Modern.js v2 中使用嵌套路由，这个 issue close 咯
