### ISSUE TITLE
[Bug]: Can't resolve '@modern-js/runtime/plugins' in module-tools

### ISSUE THREAD

**Issue by Linginnn** [web-infra-dev/modern.js#2887]
### 版本信息

```sh
2.4版本
```

### 问题详情

![image](https://user-images.githubusercontent.com/16818104/218665092-311b1ad5-a3b1-454c-ac4f-d80ddbf2151e.png)
这个路径已经没有了，这两个方法也没有导出
启用storybook，方法没有导出，跑不起来

### 复现链接

无

**Comment by chenjiahan** [comment]
麻烦确认下是否已经在 modern.config.ts 里注册了 storybookPlugin：

```ts
import storybookPlugin from '@modern-js/plugin-storybook';

export default defineConfig({
  plugins: [storybookPlugin()],
});
```

如果注册后有问题，可以提供一个最小复现仓库看下

**Comment by targeral** [comment]
这里目前需要将 `runtime` 也在插件中注册一下，应该就可以正常启动了。

``` js
import storybookPlugin from '@modern-js/plugin-storybook';
import runtime from '@modern-js/runtime/cli';

export default defineConfig({
  plugins: [storybookPlugin(), runtime()],
});
```

目前 storybook 的运行会依赖 runtime 插件，这里我们会进行优化，使得对于 runtime 的依赖变成可选或者不需要手动注册。
