### ISSUE TITLE
[RFC]: expose `useLang` hook in `doc_tools` 

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/modern.js#3006]
### What problem does this feature solve?

The `useLang`  hook could not be implemented in user-land easily because the user could not get in touch with the `DataContext`.

https://github.com/modern-js-dev/modern.js/blob/dcad8870240fbb35f889cb4d67e70445e2c37a7d/packages/cli/doc-core/src/runtime/hooks.ts#L15-L25

This makes abstraction in i18n harder.

https://github.com/modern-js-dev/rspack-website/pull/102/files#diff-b555dea0bf068be6cdcab9944f6633525911da1d2c6262d2b78c1a4a076d7beaR5

### What does the proposed API look like?

```js
import { useLang } from '@modern-js/doc-tools'
```

**Comment by sanyuan0704** [comment]
done

**Comment by chenjiahan** [comment]
Documentation: https://modernjs.dev/doc-tools/api/api-runtime.html#uselang
