### ISSUE TITLE
[Bug]: doc-tools is using last h1 title as the document title

### ISSUE THREAD

**Issue by zoolsher** [web-infra-dev/modern.js#3062]
### Version

```sh
@modern-js/rspack-doc@1.0.0 /Users/bytedance/Projects/rspack-website
└── @modern-js/doc-tools@0.0.0-next-20230302100214 -> ./node_modules/.pnpm/@modern-js+doc-tools@0.0.0-next-20230302100214_typescript@4.9.4/node_modules/@modern-js/doc-tools
```

### Details

I created two H1 title in the same document. The expected behavior is using the first one as document title. Instead of that, doc-tools are using the last one.

![image](https://user-images.githubusercontent.com/9161085/223005076-9f710034-2a35-42f9-b2a7-6a3580f837bf.png)

### Reproduce link

skip

### Reproduce Steps

skip

**Comment by sanyuan0704** [comment]
The problem has been solved in https://github.com/web-infra-dev/modern.js/pull/3066
