### ISSUE TITLE
[Bug]: The only valid numeric escape in strict mode is '\0'

### ISSUE THREAD

**Issue by zhangxuan615** [web-infra-dev/modern.js#3082]
### 版本信息

```sh
myapp3@0.1.0 C:\Users\abcd\Desktop\webInfra\myapp3
└── @modern-js/app-tools@2.7.0
```

### 问题详情

![image](https://user-images.githubusercontent.com/40533669/223473218-0ead2ea6-ce82-4ebc-bfe1-3309ff399805.png)

### 复现链接

the lastest version

### 复现步骤

yarn dev

**Comment by zhangxuan615** [comment]
按照 “创建项目”（https://modernjs.dev/tutorials/first-app/c01-start.html）第一步就遇到了这个问题，太糟心了

**Comment by zllkjc** [comment]
好的，我们来排查一下

**Comment by yimingjfe** [comment]
这个问题我们看下，可以先把 ssr 关掉

**Comment by chenjiahan** [comment]
已修复，可以升级试一下
