### ISSUE TITLE
[Bug]: 无法在一个项目中同时使用 Modernjs 的 app-tools 和 doc-tools

### ISSUE THREAD

**Issue by chhpt** [web-infra-dev/modern.js#3151]
### 版本信息

```sh
modern-doc-app@0.1.0
├── @modern-js/app-tools@2.8.0 -> ./node_modules/.pnpm/@modern-js+app-tools@2.8.0_c1a0ab078636c04037f749460a3ab884/node_modules/@modern-js/app-tools
└─┬ @modern-js/runtime@2.8.0 -> ./node_modules/.pnpm/@modern-js+runtime@2.8.0_ddd64c4f197c566c083a1907de4effd2/node_modules/@modern-js/runtime
  └── @modern-js/app-tools@2.8.0 deduped -> ./node_modules/.pnpm/@modern-js+app-tools@2.8.0_c1a0ab078636c04037f749460a3ab884/node_modules/@modern-js/app-tools
```

### 问题详情

尝试在一个项目中使用 Modernjs 开发应用和文档，配置出现异常
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/19288423/225195401-7f11593e-71fc-4203-86fa-82e839f51244.png">

### 复现链接

https://github.com/chhpt/modernjs-doc-app.git

### 复现步骤

1. 安装依赖
2. 启动 dev，打开 http://localhost:8080/，出现的是应用 Demo，无法查看文档

**Comment by chenjiahan** [comment]
目前多个工程方案是不能在同一个配置文件里使用的哈，因为他们都会注册 dev/build 等命令，如果注册到一起，会产生命令冲突的。

你可以创建一个单独的 modern.doc.config.ts 文件，在这里面注册 docTools，然后执行 `modern dev --config ./modern.doc.config.ts` 来运行文档。

**Comment by chhpt** [comment]
遇到报错了，--config 不支持
<img width="852" alt="image" src="https://user-images.githubusercontent.com/19288423/226829869-0297ab8d-832c-45ab-ba3b-ed14b7f5ea4b.png">

**Comment by chenjiahan** [comment]
这里应该是 doc-tools 没支持 --config 导致的，我们处理下

**Comment by chenjiahan** [comment]
已在 2.10.0 版本支持
