### ISSUE TITLE
[RFC]: Module Tools 支持构建 Vue3 组件

### ISSUE THREAD

**Issue by 94ashui** [web-infra-dev/modern.js#3227]
### 这个功能解决了什么问题？

开发 Vue3 组件

### 你期望的 API 是什么样子的？

提供配置或者插件支持开发 Vue3 组件

**Comment by chenjiahan** [comment]
后续考虑通过插件的形式来支持 Vue 3 组件构建，@10Derozan

**Comment by 10Derozan** [comment]
I'll support it this month.
