### ISSUE TITLE
[Bug]: svg Component 的 viewBox 字段丢失

### ISSUE THREAD

**Issue by xalanq** [web-infra-dev/modern.js#3254]
### 版本信息

```sh
feihan-im-landing-page@0.1.0 
├── @modern-js/app-tools@2.10.0 -> ./node_modules/.pnpm/@modern-js+app-tools@2.10.0_ygqkwb4gg3aean7xjfdauovyqq/node_modules/@modern-js/app-tools
└─┬ @modern-js/runtime@2.10.0 -> ./node_modules/.pnpm/@modern-js+runtime@2.10.0_dgjuf3aqqre24bd27wvsbnxpoe/node_modules/@modern-js/runtime
  └── @modern-js/app-tools@2.10.0 deduped -> ./node_modules/.pnpm/@modern-js+app-tools@2.10.0_ygqkwb4gg3aean7xjfdauovyqq/node_modules/@modern-js/app-tools
```

### 问题详情

![image](https://user-images.githubusercontent.com/30496124/227731080-d8fe70fa-dbc8-469b-859f-2b145d39df53.png)
![image](https://user-images.githubusercontent.com/30496124/227731094-a0034624-ae24-40af-a534-780438ab07da.png)
![image](https://user-images.githubusercontent.com/30496124/227731127-d27be81e-3a5a-4a68-9917-a2150df0af22.png)
![image](https://user-images.githubusercontent.com/30496124/227731984-23496e20-b865-4f3f-9215-9f71342d137e.png)

看了下源码，应该是用 svgo 处理 svg 图片的时候，因为 svgo 默认开启了 removeViewBox 参数导致的，https://github.com/svg/svgo#built-in-plugins

提问：在 modern.js 里怎么配置这个 svgo 的参数？

### 复现链接

无

### 复现步骤

1. 随便找一个带有 viewport 的图片，比如
```html
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="4"
  xmlns="http://www.w3.org/2000/svg">
  <path d="M5 10H43M5 24H43M5 38H43" />
</svg>
```
2. 用最新的 modern.js，通过下面的方法导入
```typescript
import { ReactComponent as IconMenuComponent } from './icon_menu.svg';
```
3. 使用 IconMenuComponent 时，会丢失掉 viewBox 字段

**Comment by chenjiahan** [comment]
应该和这个改动有关：https://github.com/web-infra-dev/modern.js/pull/3155

@Asuka109 看下

**Comment by Asuka109** [comment]
svgo 的压缩能力应该是默认开启且集成到框架的，可以考虑新增 `output.svgo` 或者 `perfermance.svgo` 的配置，然后 deprecate 图片压缩插件里的 svg 配置 @chenjiahan @xalanq

**Comment by Asuka109** [comment]
@chenjiahan 我测试有 30 个复杂 svg 文件的 case，看起来 svgo 对性能影响不大

```bash
rm {RSPACK,WEBPACK}_{WITHOUT,WITH}_SVGO.md
for i in {0..3}; do
  USE_RSPACK=1 USE_SVGO=0 time pnpm build 2>>RSPACK_WITHOUT_SVGO.md;
  USE_RSPACK=1 USE_SVGO=1 time pnpm build 2>>RSPACK_WITH_SVGO.md;
  USE_RSPACK=0 USE_SVGO=0 time pnpm build 2>>WEBPACK_WITHOUT_SVGO.md;
  USE_RSPACK=0 USE_SVGO=1 time pnpm build 2>>WEBPACK_WITH_SVGO.md;
done
```

```plaintext
RSPACK_WITHOUT_SVGO.md
        5.73 real         9.14 user         1.50 sys
        6.13 real         9.48 user         1.57 sys
        6.27 real         9.44 user         1.63 sys
        6.22 real         9.21 user         1.64 sys
RSPACK_WITH_SVGO.md
        5.68 real         9.12 user         1.51 sys
        5.75 real         9.13 user         1.52 sys
        5.97 real         9.32 user         1.56 sys
        6.12 real         9.13 user         1.57 sys
WEBPACK_WITHOUT_SVGO.md
       10.93 real        27.68 user         3.37 sys
       11.43 real        28.22 user         3.52 sys
       11.53 real        27.77 user         3.60 sys
       11.35 real        27.75 user         3.51 sys
WEBPACK_WITH_SVGO.md
       11.00 real        28.32 user         3.37 sys
       11.11 real        28.00 user         3.38 sys
       11.94 real        28.67 user         3.70 sys
       11.47 real        28.08 user         3.52 sys
```

**Comment by chenjiahan** [comment]
okk，那可以默认启用了

**Comment by xalanq** [comment]
> @chenjiahan 我测试有 30 个复杂 svg 文件的 case，看起来 svgo 对性能影响不大
> 
> ```shell
> rm {RSPACK,WEBPACK}_{WITHOUT,WITH}_SVGO.md
> for i in {0..3}; do
>   USE_RSPACK=1 USE_SVGO=0 time pnpm build 2>>RSPACK_WITHOUT_SVGO.md;
>   USE_RSPACK=1 USE_SVGO=1 time pnpm build 2>>RSPACK_WITH_SVGO.md;
>   USE_RSPACK=0 USE_SVGO=0 time pnpm build 2>>WEBPACK_WITHOUT_SVGO.md;
>   USE_RSPACK=0 USE_SVGO=1 time pnpm build 2>>WEBPACK_WITH_SVGO.md;
> done
> ```
> 
> ```
> RSPACK_WITHOUT_SVGO.md
>         5.73 real         9.14 user         1.50 sys
>         6.13 real         9.48 user         1.57 sys
>         6.27 real         9.44 user         1.63 sys
>         6.22 real         9.21 user         1.64 sys
> RSPACK_WITH_SVGO.md
>         5.68 real         9.12 user         1.51 sys
>         5.75 real         9.13 user         1.52 sys
>         5.97 real         9.32 user         1.56 sys
>         6.12 real         9.13 user         1.57 sys
> WEBPACK_WITHOUT_SVGO.md
>        10.93 real        27.68 user         3.37 sys
>        11.43 real        28.22 user         3.52 sys
>        11.53 real        27.77 user         3.60 sys
>        11.35 real        27.75 user         3.51 sys
> WEBPACK_WITH_SVGO.md
>        11.00 real        28.32 user         3.37 sys
>        11.11 real        28.00 user         3.38 sys
>        11.94 real        28.67 user         3.70 sys
>        11.47 real        28.08 user         3.52 sys
> ```

主要还是希望能开放 svgo 的配置吧，希望能尽快加上～

**Comment by chenjiahan** [comment]
这个问题已经在 v2.12.0 版本修复了，可以升级一下
