### ISSUE TITLE
[Bug]: can not close dark mode in doc core

### ISSUE THREAD

**Issue by 10Derozan** [web-infra-dev/modern.js#3280]
### Version

```sh
@modern-js/doc-core @latest
```

### Details

I want to close dark mode and set `themeConfig.darkmode:false`, but it is not valid.

### Reproduce link

empty

### Reproduce Steps

1. `doc.themeConfig.darkMode`: false
2. In a doc project dir, run `modern dev`
3. Can also enable darkMode.

**Comment by sanyuan0704** [comment]
I'll fix it.
