### ISSUE TITLE
[Bug]: Windows 下使用 Rspack 构建报错

### ISSUE THREAD

**Issue by hb-bobo** [web-infra-dev/modern.js#3321]
### 版本信息

```sh
@modern-js/app-tools@2.11.0
```

### 问题详情

cli不至于新生成的还报错把
Compile Error:
系统找不到指定的路径。 (os error 3)

### 复现链接

null

### 复现步骤

Need to install the following packages:
  @modern-js/create
Ok to proceed? (y) y
? 请选择你想创建的工程类型 Web 应用
? 请选择开发语言 TS
? 请选择包管理工具 npm
? 请选择构建工具 Rspack (实验性)
[INFO] git 仓库初始化成功
[INFO] 创建成功！

**Comment by 9aoy** [comment]
windows 下实现有问题，已修复，下个版本更新 https://github.com/web-infra-dev/rspack/issues/2558

**Comment by lycHub** [comment]
> 
你好，下版本啥时发，急用

**Comment by lycHub** [comment]
> windows 下实现有问题，已修复，下个版本更新 [web-infra-dev/rspack#2558](https://github.com/web-infra-dev/rspack/issues/2558)

你好，请问下版本啥时发，项目急用，谢谢

**Comment by 9aoy** [comment]
着急的话，可以先用1.10.0版本，或者切换到webpack构建。modern.js通常是每周四发版，这个问题因为依赖rspack发版，等rspack发布，modernjs 再发版，最早也要周一偏晚一点时间

**Comment by 9aoy** [comment]
fixed in [2.12.0](https://github.com/web-infra-dev/modern.js/releases/tag/v2.12.0)
