### ISSUE TITLE
[Bug]: Failed to resolve fs... node api

### ISSUE THREAD

**Issue by bluelong001** [web-infra-dev/modern.js#3350]
### 版本信息

```sh
devDependencies:
@modern-js/app-tools 2.9.0
```

### 问题详情

1.bff + express
api/lambda/hello.ts

const fs = require('fs');

export const get = async () => {
  console.log(fs);
  return { code: 10000 };
};

2.src/routes/page.tsx
import { get as hello } from '@api/hello';

onSubmit(){
hello();
}

3.error:
Failed to resolve fs 

![image](https://user-images.githubusercontent.com/36355363/229733071-2155c430-d1b4-420e-a59c-0f1d44d0894b.png)

### 复现链接

.

### 复现步骤

1.  run 'pnpm run dev'

**Comment by chenjiahan** [comment]
Can you provide a reproduce link for this issue?
