### ISSUE TITLE
[Bug]: 2.11.0 doc-tools 编译时 modern.config.ts 内的 doc.themeConfig.sidebar 类型校验会报错

### ISSUE THREAD

**Issue by xalanq** [web-infra-dev/modern.js#3355]
### 版本信息

```sh
"devDependencies": {
    "@modern-js/doc-tools": "^2.11.0",
    "typescript": "^5.0.3"
  }
```

### 问题详情

当 modern.config.ts 里这样写时：

![image](https://user-images.githubusercontent.com/30496124/230116004-c882d1cf-22e3-4ce6-b6e3-d3207fc35871.png)

无法过编译：

![image](https://user-images.githubusercontent.com/30496124/230116239-fedc7673-73e3-4089-a764-8c5c5b38446c.png)

可是，官方文档写的是可以填字符串的：

![image](https://user-images.githubusercontent.com/30496124/230116350-0621c54b-87f3-451c-a19e-f32ff201a94f.png)

并且你们自己的文档站点也是这样干的：

https://github1s.com/web-infra-dev/modern.js/blob/main/packages/document/doc-tools-doc/modern.config.ts

### 复现链接

无

### 复现步骤

照着你们的文档，新建一个项目，新建一些路由文件，然后按照上面的图填写 sidebar 就会报错

**Comment by sanyuan0704** [comment]
get，我们修复下这个问题哈
