### ISSUE TITLE
[Bug]: 2.11.0 doc-tools 的 doc.themeConfig.darkMode: false 不生效

### ISSUE THREAD

**Issue by xalanq** [web-infra-dev/modern.js#3356]
### 版本信息

```sh
"devDependencies": {
    "@modern-js/doc-tools": "^2.11.0",
    "typescript": "^5.0.3"
  }
```

### 问题详情

将 doc.themeConfig.darkMode 设置为 false 时，白天黑夜模式的按钮仍然在导航栏

![image](https://user-images.githubusercontent.com/30496124/230117507-5bdfa634-2942-4702-8835-7e2cb2e92c6f.png)

应该是之前的配置路径是 doc.darkMode 现在改成了 doc.themeConfig.darkMode 导致失效了

### 复现链接

无

### 复现步骤

如描述

**Comment by sanyuan0704** [comment]
这个问题已经修复了https://github.com/web-infra-dev/modern.js/pull/3334

**Comment by chenjiahan** [comment]
已经发布了修复版本 2.12.0，可以试试哈
