### ISSUE TITLE
[Bug]: Module Tools 文档疑似错误

### ISSUE THREAD

**Issue by chhpt** [web-infra-dev/modern.js#3375]
### 版本信息

```sh
无
```

### 问题详情

[如何处理第三方依赖](https://modernjs.dev/module-tools/guide/advance/external-dependency.html) 的描述中，peerDependencies 是否应该是 devDependencies，因为 devDependencies 里的依赖才会默认打包

<img width="815" alt="image" src="https://user-images.githubusercontent.com/19288423/230579860-c4f2ac99-6f67-422e-a160-8497027f2028.png">

### 复现链接

https://modernjs.dev/module-tools/guide/advance/external-dependency.html

### 复现步骤

无

**Comment by 10Derozan** [comment]
感谢指出，你说的是对的，我更改一下

**Comment by 10Derozan** [comment]
这几天我会再review文档和相关功能
