### ISSUE TITLE
[Bug]: repack 下 BFF 失效

### ISSUE THREAD

**Issue by baranwang** [web-infra-dev/modern.js#3380]
### 版本信息

```sh
└── @modern-js/app-tools@2.12.0  -> /Users/baran/Documents/workspace/vec-text-fe/node_modules/.pnpm/registry.npmjs.org+@modern-js+app-tools@2.12.0_rea_hitbrxb7nl57y5s7zo5yxeacwm/node_modules/@modern-js/app-tools
```

### 问题详情

repack 下调用 @api 下的方法，没有按预期调用 bff 接口，而且直接执行了对应的方法

### 复现链接

https://github.com/baranwang/demo

### 复现步骤

repack 下调用 @api 下的方法，没有按预期调用 bff 接口，而且直接执行了对应的方法

**Comment by chenjiahan** [comment]
Hi，能否提供一个复现仓库，方便我们进行排查

**Comment by baranwang** [comment]
@chenjiahan 补充到上面的信息里了，环境是 node 18
https://github.com/baranwang/demo/blob/main/src/routes/page.tsx#L6-L8 调用了请求，控制台可以看到实际并没有发出请求，而是直接执行的方法

**Comment by bluelong001** [comment]
也有一样的问题，在线等，这种方式导致node api不可用比如node的fs库之类

**Comment by chenjiahan** [comment]
好的，我们确认下这个问题，稍等

**Comment by chenjiahan** [comment]
修复咯，本周四会发一个修复版本
