### ISSUE TITLE
[Bug]: The aside bar do not generate title for imported md file

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/modern.js#3389]
### Version

```sh
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 111.0.5563.146
  npmPackages:
    @modern-js/doc-tools: latest
```

### Details

If we import a `.md` file into the current file, the doc-tools will not generate an aside bar for the imported md.

For example, import a `.md` file from a package:

```mdx
import Main from '@modern-js/builder-doc/docs/en/config/tools/webpack.md';

<Main />
```

And the right aside bar is empty:

![image](https://user-images.githubusercontent.com/7237365/230873049-f9233d10-1699-46bf-bd0b-0a12efd83030.png)

### Reproduce link

https://modernjs.dev/en/configure/app/tools/webpack.html

### Reproduce Steps

1. import a md file
2. pnpm run dev

**Comment by sanyuan0704** [comment]
目前已经解决。在 [#3480](https://github.com/web-infra-dev/modern.js/pull/3480/files#diff-83d3eef494f6dbc908a9da313a6e6d19e86beca442ab64fd4e72657f790c6f12R22-R32) 中将 MDX 内容铺平后用提取其 
toc，作为页面的 toc 数据。

![image](https://user-images.githubusercontent.com/39261479/232997998-9c7847b2-a5d5-40f5-8eac-752de1538d92.png)
