### ISSUE TITLE
[RFC]: modernjs doc 支持最后更新时间

### ISSUE THREAD

**Issue by xstnet** [web-infra-dev/modern.js#3456]
### 这个功能解决了什么问题？

希望在页面的下方增加显示最后更新时间， 或者现在可以传通过插件实现吗？

### 你期望的 API 是什么样子的？

{frontmatter.lastUpdateTime}

**Comment by sanyuan0704** [comment]
这周来支持一下哈，目前还没有对应的插件钩子

**Comment by xstnet** [comment]
我研究了一下， 不过失败了, 下面是研究过程：

创建一个 `LastUpdateTime`组件， 并在其中使用 `usePageData` hooks成功拿到调用页面的 `filepath`, 奈何浏览器端不能用`fs`模块， 所以无法获取文件的更新时间，
 
 我又设想搞个插件， 把所有的文件更新时间保存到环境变量中，然后在`LastUpdateTime`组件中通过`Map[path]`的方式取得值， 不过不知道怎么写， 而且组件中也不能用`process.env`, 好像是没有注入， 并且也没有获取全局变量的方法
 
上面的方法能成功的话，我是打算使用自定义主题， 在布局中把这个组件插入进去
或者说可以在`usePageData`这个钩子中返回文件的`stat`信息？

我也尝试了`globalUIComponents`全局组件插件， 不过好像只在build的时候才有用(因为我看到打印信息了)， 但是对生成的页面没什么影响


下面是我关于实现方式的想法： 
1. 在`usePageData`中返回文件的stat信息
2. 内置一个 `<LastUpdateTime/>`之类的组件， 就像内置的`<Tabs>`一样
3. 加入到配置中， 开启后直接由底层实现
4. 通过插件实现

知识有限， 目前就想出这么几个，仅供参考

**Comment by sanyuan0704** [comment]
这个功能已经支持了 https://github.com/web-infra-dev/modern.js/pull/3480
