### ISSUE TITLE
[RFC]:  可以支持不同版本内容的对比功能

### ISSUE THREAD

**Issue by baixjian** [web-infra-dev/modern.js#3468]
### 这个功能解决了什么问题？

rt

### 你期望的 API 是什么样子的？

rt

**Comment by chenjiahan** [comment]
可以具体描述下你的需求场景吗？

**Comment by chenjiahan** [comment]
由于提供信息较少，这个 issue 先关闭了，后续有更多信息可以重新打开。

**Comment by baixjian** [comment]
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/109275788/236610177-e8d093e0-ecbd-4012-8828-df5d613dddaa.png">
sorry ，回复晚了， 例如图中所示， 文档版本更新后的对比功能

**Comment by chenjiahan** [comment]
get，这个功能我们目前没有计划支持呢，在社区开源的文档框架中，似乎不太有类似的能力。
