### ISSUE TITLE
[RFC]: 支持 Document.tsx 注入注释类文本.

### ISSUE THREAD

**Issue by SingleMai** [web-infra-dev/modern.js#3495]
### 这个功能解决了什么问题？

在前端应用构建时希望给 index.html 支持上一些注释类的文案，主要的作用是作为一种占位符，用于网关侧允许去做一些数据预注入的事情。

### 你期望的 API 是什么样子的？

有一个类似的组件标签可以传递不被转译的注释文案。而且实际渲染后不含该标签。
<Head>
    <Comment>{''}</Comment>
</Head>

最终输出
<head>
    
</head>

**Comment by chenjiahan** [comment]
今天会发布一个支持 `Comment` 的新版本

**Comment by chenjiahan** [comment]
已发布 2.14.0 版本支持 `Comment` 组件
