### ISSUE TITLE
[Bug]: 测试出的一些使用问题合集

### ISSUE THREAD

**Issue by RyanHo97** [web-infra-dev/modern.js#3532]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 4.59 GB / 15.87 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @modern-js/doc-tools: 2.13.1 => 2.13.1
```

### 问题详情

1.emoji符号支持🖼，这个图标未能正确显示。
2.未能在config.ts中支持html解析，会变成字符串输出
3.手机端响应式网页布局问题，出现左右空余空间
4.modern.config.ts中设置好路径跳转后发现页面并未生成，只有blog.md可以访问正常显示，更深一级无法显示

### 复现链接

已在步骤部分提供

### 复现步骤

1.复现方式：直接可在markdown首页填写

2.复现方式：`      footer: {
        // 页脚的文案
        // Footer text
        message: "Made with "+"<a href='meng.html'>❤️</a>"+" by Ryanho97",
      },`

3.复现方式：运行之后，用模拟手机端访问
   解决方式：将首页中的`<div class="mask_af0b7" style="left: 50%;"></div>`删掉行内样式即可

4.配置文件节选：
    ```
    function getNavConfig(lang: "zh" | "en") {
      const { getText, getLink } = getI18nHelper(lang);
      return [
        {
          text: getText("首页", "Home"),
          link: getLink("/"),
        },
        {
          text: getText("博客", "Multi-level"),link:getLink("/blog/blog"),
          items: [
            {
              text: getText("HTML", "Submenu1"),
              link: getLink("/blog/html/html"),
            },
            {
              text: getText("CSS", "Submenu2"),
              link: getLink("/blog/css/css"),
            },
          ],
        },
      ];
    }

  文件目录结构：
![文件目录结构](https://user-images.githubusercontent.com/49436413/233631117-4c375694-25f0-4391-9782-6e2b3aa16a5a.png)

**Comment by chenjiahan** [comment]
感谢反馈~ 我们会在下周 check 这几个问题

**Comment by chenjiahan** [comment]
> 1.emoji符号支持🖼，这个图标未能正确显示。

这个问题我 check 了下，没能复现出来，可以给个复现链接吗

**Comment by chenjiahan** [comment]
> 3.手机端响应式网页布局问题，出现左右空余空间

这个在最新版本中已经修复了

**Comment by chenjiahan** [comment]
> 4.modern.config.ts中设置好路径跳转后发现页面并未生成，只有blog.md可以访问正常显示，更深一级无法显示

这个问题麻烦也给个复现链接哈，光看配置比较难排查

**Comment by RyanHo97** [comment]
> > 1.emoji符号支持🖼，这个图标未能正确显示。
> 
> 这个问题我 check 了下，没能复现出来，可以给个复现链接吗

这个直接放在doc首页分栏里面使用即可，是以一种无颜色且线条简单的形式出现的，您可以看到在github上面，这个既有颜色又有精细的笔画。

**Comment by RyanHo97** [comment]
> > 3.手机端响应式网页布局问题，出现左右空余空间
> 
> 这个在最新版本中已经修复了

这个没问题了

**Comment by RyanHo97** [comment]
> > 4.modern.config.ts中设置好路径跳转后发现页面并未生成，只有blog.md可以访问正常显示，更深一级无法显示
> 
> 这个问题麻烦也给个复现链接哈，光看配置比较难排查

这个在后续的测试中也没问题了

**Comment by RyanHo97** [comment]
> 🖼

1补图，我不确定，是不是我环境问题，还是这个应该这样显示：
![image](https://github.com/web-infra-dev/modern.js/assets/49436413/1a8b6c46-f4c0-4def-a88d-199618061079)
