### ISSUE TITLE
[Bug]: 使用命名为中文的md文件，侧边栏目录切换后消失问题

### ISSUE THREAD

**Issue by RyanHo97** [web-infra-dev/modern.js#3534]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 7.81 GB / 15.87 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @modern-js/doc-tools: 2.13.1 => 2.13.1
```

### 问题详情

**1.侧边栏目录点击切换后消失，如图：**
这个是没问题地方
![1](https://user-images.githubusercontent.com/49436413/233653596-f5ae42d7-2faa-47de-a9a7-7e60e71898db.png)

这是有问题的地方
![2](https://user-images.githubusercontent.com/49436413/233653802-8794e3ef-e97c-4483-999a-60b9eceb055e.png)

### 复现链接

已在步骤部分提供

### 复现步骤

侧边栏的配置代码：
`function getSidebarConfig(lang: "zh" | "en") {
  const { getText, getLink } = getI18nHelper(lang);
  // 注: 侧边栏配置可以嵌套，子菜单字段为 items
  // Note: The sidebar configuration can be nested, and the sub-menu field is items
  return {
    "/": [
      {
        text: getText("Blog", "Quick Start"),
        link: getLink("/blog/blog"),
      },
      {
        text: getText("HTML", "Basic"),
        link: getLink("/blog/html/html"),
        items: [
          {text: getText("1.HTML介绍", "Install"),link: getLink("/blog/html/01html-base"),},
          {text: getText("2.HTML元素", "Install"),link: getLink("/blog/html/02html-元素"),},
          {text: getText("3.HTML属性", "Install"),link: getLink("/blog/html/03html-属性"),},
          {text: getText("4.HTML标题", "Install"),link: getLink("/blog/html/04html-title"),},
          {text: getText("5.HTML段落", "Install"),link: getLink("/blog/html/05html-段落"),},
          {text: getText("6.HTML文本格式化", "Install"),link: getLink("/blog/html/06html-文本格式化"),},
          {text: getText("7.HTML超链接", "Install"),link: getLink("/blog/html/07html-链接"),},
          {text: getText("8.HTML头部", "Install"),link: getLink("/blog/html/08html-头部"),},
        ],
      },
      {
        text: getText("进阶", "Advanced"),
        link: getLink("/guide/advanced"),
      },
    ],
  };
}`
代码截图：
![code](https://user-images.githubusercontent.com/49436413/233654182-253338d7-826c-4e53-a34b-940b64db516d.png)

**Comment by sanyuan0704** [comment]
fixed in https://github.com/web-infra-dev/modern.js/pull/3568
