### ISSUE TITLE
[Bug]:侧边栏手机端使用逻辑建议 

### ISSUE THREAD

**Issue by RyanHo97** [web-infra-dev/modern.js#3535]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 7.77 GB / 15.87 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @modern-js/doc-tools: 2.13.1 => 2.13.1
```

### 问题详情

现在当我手机端打开侧边栏切换新的页面之后，并不能把菜单关闭取消状态，需要再用手去点击侧面或者菜单按钮，仅是建议。

切换之前：
![1](https://user-images.githubusercontent.com/49436413/233656594-f52380bc-43ec-4386-9d04-6728dc5bdea8.png)

切换之后：
![2](https://user-images.githubusercontent.com/49436413/233656619-80cc457f-888e-4921-bbd7-bd784ad6a761.png)

### 复现链接

已在步骤部分提供

### 复现步骤

打开手机端侧边栏切换复现

**Comment by chenjiahan** [comment]
嗯嗯，这个交互可以优化下，切换后自动关闭更加合理些

**Comment by sanyuan0704** [comment]
#3539
