### ISSUE TITLE
[Bug]: Error: Cannot find module 'react/jsx-runtime'

### ISSUE THREAD

**Issue by coderweiweihu** [web-infra-dev/modern.js#3536]
### 版本信息

```sh
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 475.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 111.0.1
    Safari: 16.1
  npmPackages:
    @modern-js/doc-tools: ^2.11.0 => 2.11.0
```

### 问题详情

when i create modernjs Doc project, i am not run the project
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/130165061/233673199-b41482c2-4ece-4bd1-ba23-78e9c97b2dcc.png">

### 复现链接

https://coderweiweihu-musical-couscous-jx4g7jqw5653pq54.github.dev/

## Project setup
```bash
pnpm run dev
```

**Comment by sanyuan0704** [comment]
这个复现地址好像打不开

**Comment by sanyuan0704** [comment]
是使用 @modern-js/create 脚手架生成的吗

**Comment by sanyuan0704** [comment]
@coderweiweihu

**Comment by chenjiahan** [comment]
As this issue is no longer active, we will close it until there is a new comment.
