### ISSUE TITLE
[RFC]: `monorepo`场景下开发和发布阶段自动处理不一样的`package.json`

### ISSUE THREAD

**Issue by zhangfisher** [web-infra-dev/modern.js#3582]
### What problem does this feature solve?

我的开源项目[flex-tools](https://github.com/zhangfisher/flex-tools)，目前已经迁移到使用`@modern-js/module-tools`进行构建，目前工作良好，

在我的下一个项目中使用了`monrepoo`多包管理，碰到这样一个需求，假设项目结构如下：

```typescript
<root>
  |-- packages
         |--app
             |-src
                |-index.ts
             package.json
      |--utils
          |-src
             |-index.ts  
          package.json
```

该工程具有`@myproject/app`和`@myproject/utils`两个包，其中`@myproject/app`依赖于`@myproject/utils`。

这样在`@myproject/app`中通过`import * from "@myproject/utils`方式来导入依赖

由于`@myproject/utils`存在于`src`中，所以我需要在`@myproject/utils`中`package.json`中指定`main="src/index.ts"`
这样我就可以在不进行`build`的情况进行调试。
但是，当我构建`@myproject/utils`时，构建结果输出在`dist`，这样我又不得不发布时将重新指定`main=dist/index.ts`

显然，问题在于开发阶段和发布阶段的`main/exports/module`等字段指向是不一样的，这样比较麻烦了.

目前我的解决方案是，通过脚本在发布后修改，类似这样：
```
    "build": "modern build && cd dist && npm pkg set main=index.js && npm pkg set module=index.mjs && npm pkg set types=index.d.ts",
```
显然这样比较不好看，如果涉及到复杂的`exports`就更不可行了，所以我想`@modern-js/module-tools`是否可以提供一个解决方案？

### What does the proposed API look like?

我想是否可以这样，在`modern.config.js`中进行配置：

`export default defineConfig({
packageJson:{
   // 在此覆盖开发阶段的packageJson文件
  // 生成新的package.json到dist下
}
})
`

**Comment by caohuilin** [comment]
@zhangfisher 你现在是使用什么进行发布的，如果是 pnpm 或者 npm 的话，在 `package.json` 中设置 `publishConfig` 应该可以解决你的问题
https://pnpm.io/package_json#publishconfig
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#publishconfig

**Comment by zhangfisher** [comment]
是我孤陋寡闻了
