### ISSUE TITLE
[Feature]: Doc support nav postion

### ISSUE THREAD

**Issue by sanyuan0704** [web-infra-dev/modern.js#3604]
### What problem does this feature solve?

Some navbar menus need to be placed on the left, not just the right.

![image](https://user-images.githubusercontent.com/39261479/236370021-a5b34e53-2d23-465a-ac82-86ee07d73573.png)

### What does the proposed API look like?

Add a `position` param in nav config：

```ts
export default {
  doc: {
    themeConfig: {
      nav: [
        {
          text: 'Guide',
          link: '/guide/',
          // left / right
          position: 'left' 
        }
      ]
    }
  }
}
```

**Comment by RyanHo97** [comment]
I will complete this issue within the next week

**Comment by chenjiahan** [comment]
🎉🎉
