### ISSUE TITLE
[Bug]: The hash on the URL is lost after compilation

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/modern.js#3677]
### Version

```sh
@modern-js/doc-tools: 2.19.0
```

### Details

After upgrading `@modern-js/doc-tools` v2.19.0, the hash of the URL is missing after compilation:

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/7f8c04c8-17a9-45f8-91ea-f07f2f9a6ae8)

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/aa42e21d-c541-41ad-9511-756988d97923)

### Reproduce link

https://github.com/web-infra-dev/modern.js

### Reproduce Steps

1. cd packages/document/builder-doc
2. pnpm run dev

**Comment by sanyuan0704** [comment]
Delete `.html` and it will work.And i will optimize the logic later.

**Comment by sanyuan0704** [comment]
#3681
