### ISSUE TITLE
[Bug]: external link added language prefix when lang in config is not match

### ISSUE THREAD

**Issue by lalalazero** [web-infra-dev/modern.js#3687]
### Version

```sh
*
```

### Details

see https://github.com/web-infra-dev/rspack-website/issues/305

### Reproduce link

https://github.com/web-infra-dev/rspack-website/issues/305

### Reproduce Steps

1. change language to zh
2. click ecosystem submenu link

**Comment by lalalazero** [comment]
it's cuased by this
![image](https://github.com/web-infra-dev/modern.js/assets/20458239/fcd37d46-49e8-4a50-8122-9d3e2ff169f6)


I think before add lang to route prefix, you should judge if it's external link (start with http protocol)

**Comment by sanyuan0704** [comment]
Thank you! I will fix it right away.

**Comment by lalalazero** [comment]
> Thank you! I will fix it right away.

三元...这 pr 我要留着自己修的... :cry: 我的第一个 pr 啊啊啊啊啊

**Comment by chenjiahan** [comment]
让三元给你再找一个😂

**Comment by sanyuan0704** [comment]
😄 下次你说下好了，让你来 pr，还有很多机会的~
