### ISSUE TITLE
[Feature]: 希望可以默认生成tailwind.config.js以支持VS Code的插件智能提示

### ISSUE THREAD

**Issue by xmsz** [web-infra-dev/modern.js#3919]
### 这个功能解决了什么问题？

<img width="928" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/5879146/7031b208-ed87-4351-91b2-eee26f6f918e">
- 需要tailwindCss的补全
- 现在需要手动创建`tailwind.config.js`有点麻烦

### 你期望的 API 是什么样子的？

- 希望启用tailwindCss的时候，自动生成这个文件

**Comment by chenjiahan** [comment]
这个场景确实需要适配一波。

除了需要创建 `tailwind.config.js`，是不是也需要把 Modern.js 里设置的 tailwindcss 默认值也填充进去嘞？这样 IDE 插件才能读取到完整的配置。

另外 modern.config.ts 里是不是得手动引用一下这个文件，设置到 tools.tailwindcss 配置项上。

**Comment by UNDERCOVERj** [comment]
还要考虑monorepo的情况，不过插件好像可以支持每个workspace单独的tailwindcss config配置

**Comment by chenjiahan** [comment]
嗯嗯，monorepo 应该是 vscode 插件考虑的事情

**Comment by chenjiahan** [comment]
I wrote a new RFC for this issue: https://github.com/web-infra-dev/modern.js/discussions/4509
