### ISSUE TITLE
[Bug]: @modern-js/e2e npm没有相关依赖包

### ISSUE THREAD

**Issue by joinxin** [web-infra-dev/modern.js#3979]
### Version

```sh
System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 135.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 112.0.2
    Safari: 15.0
```

### Details

通过npm安装依赖时发现此依赖无法安装，查询npm源，也没有相关包

### Reproduce link

https://www.npmjs.com/package/@modern-js/e2e

### Reproduce Steps

<img width="1256" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/49011292/479a9796-aa28-4ccc-93af-fa5131ed1545">

**Comment by chenjiahan** [comment]
这个是 optional 的 peerDependencies，现代包管理器应该不会安装 optional 依赖，请问你使用的 npm 版本是多少嘞

**Comment by chenjiahan** [comment]
我们可以在下个版本把这个 peerDependencies 移除掉

**Comment by joinxin** [comment]
npm 8.19.4

**Comment by chenjiahan** [comment]
我看了下 npm v7 就支持 peerDependenciesMeta 的，按理说不会有问题

https://github.com/npm/cli/commit/052e977b9d071e1b3654976881d10cd3ddcba788

**Comment by chenjiahan** [comment]
问题不大，我们下个版本会将 @modern-js/e2e 从 peerDependencies 里移除

**Comment by chenjiahan** [comment]
Fixed in v2.23.1
