### ISSUE TITLE
[Bug]: Optimize the error message prompt for @modern-js/module-tools or @modern-js/libuild

### ISSUE THREAD

**Issue by targeral** [web-infra-dev/modern.js#4049]
### Version

```sh
ystem:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 92.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5
npmPackages:
    @modern-js/module-tools: 2.24.0 => 2.24.0
    @modern-js/plugin-testing: 2.24.0 => 2.24.0
```

### Details

When there is an error syntax in the less file, the error message cannot be located.

![image](https://github.com/web-infra-dev/modern.js/assets/9037723/ae69b30f-cb41-4fbb-ba61-6d887911d568)

### Reproduce link

None

### Reproduce Steps

None

**Comment by 10Derozan** [comment]
Fixed in https://github.com/web-infra-dev/modern.js/pull/5230
