### ISSUE TITLE
[Bug]: 微前端 子应用根路由不转跳

### ISSUE THREAD

**Issue by StringKe** [web-infra-dev/modern.js#4107]
### 版本信息

```sh
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.33 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67
    Safari: 16.5.1
  npmPackages:
    @modern-js/eslint-config: 2.25.1 => 2.25.1 
    @modern-js/monorepo-tools: 2.25.1 => 2.25.1 
    @modern-js/tsconfig: 2.25.1 => 2.25.1
```

### 问题详情

当主页面进行切换路由，切换的路由为子应用的根路径的时候切换无效

product/print/form/design/ => PrintProductDesign 中的 /
product/print/form/design/test => PrintProductDesign 中的 /test

从主应用中切换 product/print/form/design/test 到 product/print/form/design/ 并不会产生路由跳转

### 复现链接

https://github.com/StringKe/micro-modrenjs-router

### 复现步骤

启动 app 内所有子应用然后打开 http://localhost:8080/

1. 访问 http://localhost:8080/
2. 通过页面切换到 [1 Sub Print Product Design /test](http://localhost:8080/product/print/form/design/test)
3. 通过页面切换到 [2 Route /bbbb](http://localhost:8080/product/print/form/design/bbbb)

这时候点击 [3 Sub Print Product Design /](http://localhost:8080/product/print/form/design) 无法切换到对应的路由中。

**Comment by nyqykk** [comment]
可以先执行一次 Garfish.run()，如果不需要根据路由自动挂在子应用能力，请不要提供 activeWhen 参数

**Comment by StringKe** [comment]
在 modern 提供的约定是路由中应该如何通过手动的方式在指定的文件中加载应用呢？

需要 activeWhen 参数么？

**Comment by nyqykk** [comment]
这是因为约定式路由里面 src 下不能有 App.tsx 文件，你把这个文件去掉

**Comment by StringKe** [comment]
我没有这个 App.tsx 文件

![CleanShot 2023-07-05 at 14 22 22@2x](https://github.com/web-infra-dev/modern.js/assets/31089228/c997190f-96e2-4b07-b4a4-38aa9d4f90ed)

**Comment by nyqykk** [comment]
你这里路径应该是 /print/app/xxx

**Comment by nyqykk** [comment]
我试了一下没什么问题，如果还不行的话，你截图看下 node_modules/main/routes.js

**Comment by StringKe** [comment]
https://github.com/StringKe/micro-modrenjs-router 我更新了一下 demo 

/product 和 /product/print 都无法加载

```
Matched leaf route at location "/product/print" does not have an element or Component. This means it will render an <Outlet /> with a null value by default resulting in an "empty" page.
```

**Comment by nyqykk** [comment]
每个 $.tsx 应该需要一个 layout.tsx 文件

**Comment by StringKe** [comment]
主应用目录
![CleanShot 2023-07-05 at 14 52 21@2x](https://github.com/web-infra-dev/modern.js/assets/31089228/75dc3a7b-c9c7-474e-a142-03917ac6fbc1)

masterApp 配置
```js
[
  { name: 'AdminProduct', entry: 'http://0.0.0.0:4002' },
  { name: 'AdminPrintDesign', entry: 'http://0.0.0.0:4004' },
  { name: 'AdminPrint', entry: 'http://0.0.0.0:4003' }
]
```

/routers/page.tsx
```typescript
const Index = () => (
    <div>
        <div>routers/page.tsx</div>
    </div>
)

export default Index
```



/routers/layout.tsx
```typescript
import { Outlet } from '@modern-js/runtime/router'

export default function Layout() {
    return (
        <div>
            <div>routers/layout.tsx</div>
            <Outlet />
            <div>routers/layout.tsx end</div>
        </div>
    )
}
```



/routers/print/layout.tsx
```typescript
import { Outlet } from '@modern-js/runtime/router'

export default function () {
    return (
        <div>
            <div>routers/print/layout.tsx</div>
            <Outlet />
            <div>routers/print/layout.tsx end</div>
        </div>
    )
}
```



/routers/print/$.tsx
```typescript
import { useModuleApps } from '@modern-js/plugin-garfish/runtime'

const Index = () => {
    const { AdminPrint } = useModuleApps()

    return (
        <div>
            <div>routers/print/$.tsx</div>
            <AdminPrint />
            <div>routers/print/$.tsx end</div>
        </div>
    )
}

export default Index

```

app/node_modules/.modern-js/main/routes.js
```js
import { lazy } from "react";


import RootLayout from "@_modern_js_src/routes/layout.tsx";


export const routes = [
  {
    "path": "/",
    "children": [
      {
        "_component": "@_modern_js_src/routes/page.tsx",
        "index": true,
        "id": "page",
        "type": "nested",
        "lazyImport": () => import(/* webpackChunkName: "page" */  "@_modern_js_src/routes/page.tsx"),
        "component": lazy(() => import(/* webpackChunkName: "page" */  "@_modern_js_src/routes/page.tsx"))
      },
      {
        "path": "print",
        "children": [
          {
            "_component": "@_modern_js_src/routes/print/$.tsx",
            "path": "*",
            "id": "print/$",
            "type": "nested",
            "lazyImport": () => import(/* webpackChunkName: "print/$" */  "@_modern_js_src/routes/print/$.tsx"),
            "component": lazy(() => import(/* webpackChunkName: "print/$" */  "@_modern_js_src/routes/print/$.tsx"))
          }
        ],
        "isRoot": false,
        "_component": "@_modern_js_src/routes/print/layout.tsx",
        "id": "print/layout",
        "type": "nested",
        "lazyImport": () => import(/* webpackChunkName: "print/layout" */  "@_modern_js_src/routes/print/layout.tsx"),
        "component": lazy(() => import(/* webpackChunkName: "print/layout" */  "@_modern_js_src/routes/print/layout.tsx"))
      }
    ],
    "isRoot": true,
    "_component": "@_modern_js_src/routes/layout.tsx",
    "id": "layout",
    "type": "nested",
    "lazyImport": null,
    "component": RootLayout
  }
];
```

具体表现
![CleanShot 2023-07-05 at 14 55 27@2x](https://github.com/web-infra-dev/modern.js/assets/31089228/e5db814e-630e-45c2-8534-4bc3bac064ac)

![CleanShot 2023-07-05 at 14 55 43@2x](https://github.com/web-infra-dev/modern.js/assets/31089228/988a9f74-e69c-48ab-be00-60da02bf0c71)

**Comment by nyqykk** [comment]
这里你的访问路径如果是 /print/xxx (xxx 是子应用的一个子路由)是可以访问到子应用的子路由的，因为 /xxx 是子应用的一个路由，这里访问 /print 没有加载 $.tsx，/print/xxx 才加载 $.tsx 符合预期吗 @yimingjfe

**Comment by StringKe** [comment]
@nyqykk 这个问题可能是这个原因。

https://github.com/StringKe/micro-modrenjs-router/tree/test1 这个 test1 分支中

@modern-js/plugin-garfish 依赖是分别在两个应用中功能添加的。

而我本地测试的项目是在 monorepo 根中添加的。

当我分别在具体的应用中加载后 路由正确了。

**Comment by nyqykk** [comment]
没太听明白，你这个项目里是在每个应用里装一个 plugin-garfish，这个会导致什么问题

**Comment by nyqykk** [comment]
你这里 $.tsx 同级可能不需要 layout.tsx，这可能会导致子应用根路由匹配不到导致404

**Comment by StringKe** [comment]
> 

我最开始是没有在每个项目里安装 plugin-garfish 导致的这个问题，在每个项目里安装之后正常

**Comment by nyqykk** [comment]
done

**Comment by nyqykk** [comment]
提醒一下，我看到你把 plugin-garfish 装到 devDependency 中了，这个需要装到 dependency 中

**Comment by StringKe** [comment]
好的。

**Comment by StringKe** [comment]
今天又一次遇到这个问题了

访问 /print 进入不了 /print/$.tsx 浏览器控制台出现警告

Matched leaf route at location "/print" does not have an element or Component. This means it will render an <Outlet /> with a null value by default resulting in an "empty" page.

**Comment by nyqykk** [comment]
去掉同级的 layout.tsx

**Comment by StringKe** [comment]
同级别没有 layout.tsx

**Comment by nyqykk** [comment]
你这里也没有 /print 呀，对应你发的这个项目里哪个路由访问不了

**Comment by nyqykk** [comment]
这里应该是个路由优先级匹配的问题，cc @yimingjfe

**Comment by nyqykk** [comment]
目前这里应该是在 $.tsx 下还有子目录时会有问题，所以 /a/b/c/d 没有问题，因为他没有子目录了，这是一个路由优先级问题

**Comment by yimingjfe** [comment]
> > 
> 
> 我简化了仓库代码
> 
> http://localhost:8080/a/b/c/d 正常 http://localhost:8080/a/b/c 出错 http://localhost:8080/a/b 出错 http://localhost:8080/a 出错

目前还不支持，环境给 Modern.js 贡献，或者等我们支持

**Comment by yimingjfe** [comment]
已支持 https://github.com/web-infra-dev/modern.js/pull/4323
