### ISSUE TITLE
[Bug]:  编译错误,  @modern-js/runtime/dist/types/router is not exported

### ISSUE THREAD

**Issue by sniper-xx** [web-infra-dev/modern.js#4108]
### 版本信息

```sh
System: windows 11
版本: 
  "@arco-design/web-react": "^2.50.0",
  "@modern-js/plugin-tailwindcss": "2.25.1",
  "@modern-js/runtime": "2.25.1",
  "axios": "^1.4.0",
  "react": "~18.2.0",
  "react-dom": "~18.2.0"
```

### 问题详情

Compile Error: 
Package path @modern-js/runtime/dist/types/router is not exported

### 复现链接

/

### 复现步骤

![image](https://github.com/web-infra-dev/modern.js/assets/70681/fdfbf443-5e0e-4147-b5f8-88ff70bc1320)

**Comment by chenjiahan** [comment]
@sniper-xx 可以提供一个复现问题的示例仓库吗~

**Comment by sniper-xx** [comment]
> @sniper-xx 可以提供一个复现问题的示例仓库吗~

已经解决。 代码问题，导入Router 函数的路径不对。
