### ISSUE TITLE
[Bug]: monorepo 项目中使用 pnpm 代码检查 eslint 无法正确工作

### ISSUE THREAD

**Issue by StringKe** [web-infra-dev/modern.js#4113]
### 版本信息

```sh
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.96 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67
    Safari: 16.5.1
  npmPackages:
    @modern-js/eslint-config: 2.25.1 => 2.25.1 
    @modern-js/monorepo-tools: 2.25.1 => 2.25.1 
    @modern-js/plugin-garfish: 2.25.1 => 2.25.1 
    @modern-js/tsconfig: 2.25.1 => 2.25.1
```

### 问题详情

pnpm 并不会在当前 workspace root 下依赖 eslint 的 cli

如果手动通过 pnpm add eslint -w -D 则 webstorm 会提示 eslint 无法加载 eslint-plugin-import 插件。

1. root 下并未依赖 eslint
![CleanShot 2023-07-03 at 17 29 15@2x](https://github.com/web-infra-dev/modern.js/assets/31089228/304ad5bf-4120-4cb4-8aa0-3c8a7b4f1d24)

2. lint-staged 读取了 node_modules/eslint 中的内容
![CleanShot 2023-07-03 at 17 30 00@2x](https://github.com/web-infra-dev/modern.js/assets/31089228/47b25281-bb67-4fd1-b2e7-95db67372b04)

如果手动添加 pnpm add eslint -D -w 则通过 webstorm 打开应用会出现 eslint-plugin-import 不存在。

### 复现链接

https://github.com/StringKe/modern-monorepo-eslint-error

### 复现步骤

提交任意 git 触发 husky 即可

**Comment by chenjiahan** [comment]
我看了下是另一个报错，这里报错信息是找不到 typescript，因为 ESLint 里有一些 typescript 相关的规则。

<img width="1083" alt="Screen Shot 2023-07-03 at 17 43 30" src="https://github.com/web-infra-dev/modern.js/assets/7237365/41230afe-fe19-4580-8d6f-0a1c0ed2b53a">

提了一个修复 PR，添加 typescript 和 tsconfig.json，你可以参考下

https://github.com/StringKe/modern-monorepo-eslint-error/pull/1

**Comment by StringKe** [comment]
![CleanShot 2023-07-03 at 18 21 54@2x](https://github.com/StringKe/modern-monorepo-eslint-error/assets/31089228/d5d77cbd-b4e4-40da-96c5-47bdedf9f367)


你能截图一下你 node_modules 文件夹么？

**Comment by chenjiahan** [comment]
我用的 pnpm v8

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/ccf3912e-d0de-4f32-b749-10721821cde1)

**Comment by chenjiahan** [comment]
I will close this issue because it is no longer active, feel free to reopen it if you have any further questions.
