### ISSUE TITLE
[Feature]: 微前端 activeWhen 参数支持函数。

### ISSUE THREAD

**Issue by StringKe** [web-infra-dev/modern.js#4115]
### 这个功能解决了什么问题？

https://www.garfishjs.org/api/registerApp#activewhen

> Garfish 将使用字符串最短匹配原则作为激活判断条件匹配子应用，各子应用的 activeWhen 参数应保持唯一（即：Garfish 能够精准匹配到当前应该激活的子应用，应避免子应用间出现 activeWhen 重合的情况；

所以当存在 /print 和 /print/product 的时候就会同时渲染两个子应用，默认 activeWhen 支持函数的方式让开发者自行控制是否需要渲染，但目前 modernjs 中未适配

### 你期望的 API 是什么样子的？

支持传递函数或者其他方案

**Comment by zhoushaw** [comment]
https://modernjs.dev/apis/app/runtime/app/define-config.html

通过运行时配置即可

**Comment by StringKe** [comment]
https://modernjs.dev/guides/basic-features/routes.html#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE

另一种方式。
