### ISSUE TITLE
[Bug]: Eslint 不支持 $.tsx 文件，这个是约定式路由中的配置。

### ISSUE THREAD

**Issue by StringKe** [web-infra-dev/modern.js#4127]
### 版本信息

```sh
None
```

### 问题详情

```
/modern-monorepo-umd-resource/apps/main/src/routes/$.tsx
  1:1  error  Filename '$.tsx' does not match the naming convention  filenames/match-regex
```

https://github.com/StringKe/modern-monorepo-umd-resource/blob/main/apps/main/src/routes/%24.tsx#L1

需要自己关闭这个规则才可以继续提交 git

### 复现链接

https://github.com/StringKe/modern-monorepo-umd-resource/blob/main/apps/main/src/routes/%24.tsx#L1

### 复现步骤

修改任意文件记录

删除 https://github.com/StringKe/modern-monorepo-umd-resource/blob/main/apps/main/src/routes/%24.tsx#L1

然后提交 git

**Comment by chenjiahan** [comment]
get，我们优化下 ESLInt 规则
