### ISSUE TITLE
[Bug]: 微前端子应用无法正确加载 umd 资源。

### ISSUE THREAD

**Issue by StringKe** [web-infra-dev/modern.js#4128]
### 版本信息

```sh
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.96 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67
    Safari: 16.5.1
  npmPackages:
    @modern-js/eslint-config: 2.25.1 => 2.25.1 
    @modern-js/monorepo-tools: 2.25.1 => 2.25.1 
    @modern-js/plugin-garfish: 2.25.1 => 2.25.1 
    @modern-js/tsconfig: 2.25.1 => 2.25.1
```

### 问题详情

子项目中使用了一些外部资源，当加载子应用的时候无法正确的加载这些 umd 脚本内容。

复线 demo 为最小实现，完整实现为 https://lowcode-engine.cn/index 将这个 lowcode-engine 作为子应用加载。

### 复现链接

https://github.com/StringKe/modern-monorepo-umd-resource

### 复现步骤

pnpm i

pnpm -r dev

访问 http://localhost:3000/sub 控制台即可查看错误。

**Comment by nyqykk** [comment]
是子应用使用 cdn 加载了第三方包中往 window 挂变量了吗，你看看常见问题 https://www.garfishjs.org/issues/#cdn-%E7%AC%AC%E4%B8%89%E6%96%B9%E5%8C%85%E6%9C%AA%E6%AD%A3%E7%A1%AE%E6%8C%82%E8%BD%BD%E5%9C%A8-window-%E4%B8%8A

**Comment by StringKe** [comment]
是的，我加入 no-entry 可以正常加载了。我这里子应用还需适配一下自己可以处理。

**Comment by StringKe** [comment]
@nyqykk 我有些已经配置了，但还是无法加载。
https://github.com/StringKe/modern-lowcode-engine

https://github.com/StringKe/modern-lowcode-engine/blob/main/apps/editor/modern.config.ts#L35-L49

我通过这样配置，在后续加载过程中 umd 资源还是有些问题

**Comment by nyqykk** [comment]
你可以先看看 cdn 加载的资源中是不是有往 window 挂变量的行为，然后加了 no-entry 以后有没有正确挂上去

**Comment by nyqykk** [comment]
> > 你可以先看看 cdn 加载的资源中是不是有往 window 挂变量的行为，然后加了 no-entry 以后有没有正确挂上去
> 
> 有这个行为，但是他其他脚本异步加载的，无法手动添加 no-entry ，我已经通过
> 
> ![CleanShot 2023-07-06 at 15 04 19@2x](https://user-images.githubusercontent.com/31089228/251371041-40280794-86e0-4720-a1b5-f0ca36a47fe4.png)
> 
> 这样的方式将所有异步加载的资源都匹配了，还是遇到一样的问题。
> 
> https://github.com/alibaba/lowcode-engine/blob/HEAD/packages/rax-simulator-renderer/src/utils/script.ts#L11-L37

你可以先定位一下具体哪里导致的
