### ISSUE TITLE
[Doc]:  `convertToRem`'s property `excludeEntries` make confusing meaning

### ISSUE THREAD

**Issue by spencerHT** [web-infra-dev/modern.js#4196]
### What problem does this feature solve?

Some users thinks that `excludeEntries` is a config to avoid some entries css wouldn't be transform to rem.  
But it works just for not inject runtime script that about auto resizing font-size at html tag into html content.

If user truly want to exclude some css away from `postcss-pxtorem`, we should add `exclude` config at `pxtorem`.

### What does the proposed API look like?

Explain clearly what `excludeEntries` is working for.

**Comment by chenjiahan** [comment]
Thanks for the feedback, we will update the document to make it more clear.
