### ISSUE TITLE
[Bug]: v4.1.0 的版本的间接依赖 json5 存在安全问题，需要升级

### ISSUE THREAD

**Issue by debugfarmer** [web-infra-dev/modern.js#4209]
### Version

```sh
-
```

### Details

-

### Reproduce link

-

### Reproduce Steps

-

**Comment by debugfarmer** [comment]
https://github.com/web-infra-dev/modern.js/blob/main/packages/server/utils/package.json#L49C1-L50C1

**Comment by chenjiahan** [comment]
get，我们看看

**Comment by chenjiahan** [comment]
这个问题需要升级 babel-plugin-module-resolver 5.0.0 才能解决，但是 5.0.0 不再支持 Node.js 14 了，而 Modern.js 目前没有停止对 Node.js 14 的支持，所以现阶段无法直接升级。

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/21908234-e95f-4fdf-92b3-33ff6a4f2b9a)

https://github.com/tleunen/babel-plugin-module-resolver/blob/master/package.json#L10-L12

这个插件用于 BFF 的 babel compiler 场景，提供 alias 处理能力，目前看来没有很好的替代品。考虑到 babel-plugin-module-resolver 本身已经不维护了，我们可能需要 fork 代码才能解决该问题。

@yimingjfe 看看有什么 idea
