### ISSUE TITLE
[Bug]: modern build have extra runtime-builder.js.map 

### ISSUE THREAD

**Issue by spencerHT** [web-infra-dev/modern.js#4213]
### Version

```sh
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.24 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.3
  npmPackages:
    @modern-js/app-tools: 2.26.0 => 2.26.0 
    @modern-js/eslint-config: 2.26.0 => 2.26.0 
    @modern-js/runtime: 2.26.0 => 2.26.0 
    @modern-js/tsconfig: 2.26.0 => 2.26.0
```

### Details

`modern build` command will output  a `builder-runtime.[hash].js.map` file, but have no `builder-runtime.f2281306.js`.     
The file is useless but output in build resources.

### Reproduce link

https://github.com/spencerHT/modern-test

### Reproduce Steps

1. excute `pnpm i`
2. excute `pnpm run build`
3. find the extra file at `dist/static/js/builder-runtime.f2281306.js.map`

**Comment by chenjiahan** [comment]
The `builder-runtime.[hash].js.map` file is used for the inlined runtime code, it is not a useless file.

Ref: https://edenx.bytedance.net/en/configure/app/output/disable-inline-runtime-chunk.html

**Comment by spencerHT** [comment]
> The `builder-runtime.[hash].js.map` file is used for the inlined runtime code, it is not a useless file.
> 
> Ref: https://edenx.bytedance.net/en/configure/app/output/disable-inline-runtime-chunk.html

I have read about [disable-inline-runtime-chunk](https://edenx.bytedance.net/en/configure/app/output/disable-inline-runtime-chunk.html) before I create this issue.   
Now production building results have some `builder-runtime` code in `html/main/index.html`, but the code is different with the builder-runtime sourcemap, and I could not find any files relative to `static/js/builder-runtime.[hash].js`.  
So I think this file is useless in production building.

**Comment by chenjiahan** [comment]
Modern.js will keep the source map of all inlined files, as the user may need to use them in some cases, such as https://github.com/web-infra-dev/modern.js/pull/1978.

From my perspective, outputting the full source maps has no negative impact.

**Comment by chenjiahan** [comment]
> but the code is different with the builder-runtime sourcemap

They are the corresponding output codes and source map, what do you mean by "is different"?
