### ISSUE TITLE
[Bug]: Unsupported TypeScript syntax after adding tool.babel for Unterminated JSX contents

### ISSUE THREAD

**Issue by beilo** [web-infra-dev/modern.js#4264]
### 版本信息

```sh
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 25.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @modern-js/builder: 2.23.0 => 2.23.0 
    @modern-js/builder-plugin-image-compress: 2.23.0 => 2.23.0 
    @modern-js/builder-plugin-node-polyfill: 2.23.0 => 2.23.0 
    @modern-js/builder-rspack-provider: 2.23.0 => 2.23.0 
    @modern-js/builder-webpack-provider: 2.23.0 => 2.23.0
```

### 问题详情

Napi Error: GenericFailure - SyntaxError:
Unterminated JSX contents

![e250ecdc-1a4d-4b48-b8c0-3a58ab42757b](https://github.com/web-infra-dev/modern.js/assets/19225489/e0c636b4-255a-4e4c-9c2b-d793678104ae)

### 复现链接

[modern-builder 2.zip](https://github.com/web-infra-dev/modern.js/files/12103307/modern-builder.2.zip)

### 复现步骤

[modern-builder 2.zip](https://github.com/web-infra-dev/modern.js/files/12103307/modern-builder.2.zip)

先执行 `npm run dev` 然后 `npm run start`

First, run the command `npm run dev`.
Then, run the command `npm run start`.

感谢大家百忙之中帮忙查看这个问题
Thank you for taking the time to help with this issue.

**Comment by chenjiahan** [comment]
@9aoy Can you help to check this issue?

**Comment by 9aoy** [comment]
<img width="475" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/22373761/a376e8fb-e82c-40b1-88ac-c6d30194da3f">

<img width="1156" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/22373761/ec499dcf-93a3-46c3-9b76-7bbce8fba179">


This error is because `isTSX` is enabled by default in modern.js, so this syntax is recognized as jsx. To avoid this behavior, you should modify the `@babel/preset-typescript` configuration, like this: 
```
        removePresets(["@babel/preset-typescript"]);
        addPresets([["@babel/preset-typescript",  {
          allowNamespaces: true,
          allExtensions: false,
          allowDeclareFields: true,
          optimizeConstEnums: true,
          isTSX: false
        }]]);
```

**Comment by vttilaxuqdo0854** [comment]
@9aoy 
按照代码更改是正确的，谢谢
The code changes are correct, thank you

**Comment by beilo** [comment]
@9aoy
按照代码更改是正确的，谢谢
The code changes are correct, thank you
