### ISSUE TITLE
[Bug]: modern SSG 生成的页面里面没有SSR的dom结构 

### ISSUE THREAD

**Issue by langzilzq** [web-infra-dev/modern.js#4302]
### 版本信息

```sh
modern 最新版
```

### 问题详情

![img_v2_992fc870-232d-4900-a53e-5159c0b1aa8g](https://github.com/web-infra-dev/modern.js/assets/44768524/27c5f445-746a-4aee-ba6a-c79411dab61b)

### 复现链接

无

### 复现步骤

1. > npx @modern-js/create@latest myapp
2. > pnpm run new
3. > ssg
4. > 改好配置
5. > pnpm run build
6. > 在产物里面只有一个空的div

**Comment by GiveMe-A-Name** [comment]
能麻烦提供下配置(modern.config.ts)吗

**Comment by langzilzq** [comment]
import { appTools, defineConfig } from '@modern-js/app-tools';
import { ssgPlugin } from '@modern-js/plugin-ssg';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig({
  runtime: {
    router: true,
  },
  output: {
    ssg: true,
  },
  plugins: [appTools(), ssgPlugin()],
});

**Comment by langzilzq** [comment]
bug查到了么

**Comment by GiveMe-A-Name** [comment]
Sorry, 有点忙忘了。这两天我看下。
