### ISSUE TITLE
[Bug]: Node 16 is no longer LTS. The current LTS is 18.x.

### ISSUE THREAD

**Issue by t1ger2080** [web-infra-dev/modern.js#4390]
### Version

```sh
NA
```

### Details

Reference: https://nodejs.org/en/blog/announcements/nodejs16-eol

Please test & modify recommended Node.js version in your README.

### Reproduce link

https://github.com/web-infra-dev/modern.js/blob/main/packages/document/module-doc/docs/en/guide/intro/getting-started.md?plain=1#L9

### Reproduce Steps

https://modernjs.dev/en/guides/get-started/quick-start

**Comment by chenjiahan** [comment]
Thanks for the feedback, we will adjust the document and recommend using Node.js 18 later.
