### ISSUE TITLE
[Bug]: 页面刷新404

### ISSUE THREAD

**Issue by beilo** [web-infra-dev/modern.js#4477]
### 版本信息

```sh
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 272.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @modern-js/builder: ^2.31.2 => 2.31.2 
    @modern-js/builder-webpack-provider: ^2.31.2 => 2.31.2
```

### 问题详情

在应用内使用a标签跳转是没问题的，但是在浏览器直接输入对应的地址会直接跳转到404页面
具体情况如下视频

Navigating within the application through employment of anchor tags presents no obstacles. However, inputting the corresponding address directly into the browser precipitates an immediate redirection to a 404 error page. The precise circumstances are delineated in the accompanying video.

https://github.com/web-infra-dev/modern.js/assets/19225489/db177d83-03c2-4349-a601-b62bb32a8033

报错信息如下：

The error message is as follows:

```sh
error   Web Server Error - Page could not be found, error = 404 Not Found, req.url = /a, req.headers = {
  host: 'localhost:8080',
  connection: 'keep-alive',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  'sec-ch-ua': '"Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"',
  'sec-ch-ua-mobile': '?0',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
  'sec-ch-ua-platform': '"macOS"',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  purpose: 'prefetch',
  'sec-fetch-site': 'same-origin',
  'sec-fetch-mode': 'no-cors',
  'sec-fetch-dest': 'empty',
  referer: 'http://localhost:8080/',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8'
}
```

### 复现链接

下面给出了最小demo

Below is provided a minimal demonstration:

### 复现步骤

[test.zip](https://github.com/web-infra-dev/modern.js/files/12396714/test.zip)

代码在rspack.js中
步骤：

The code resides within the "rspack.js" file.
Sequence of actions:

npm i
npm start

感谢各位的帮助

Gratitude for the assistance extended by all.

**Comment by chenjiahan** [comment]
通常来说开启 [historyApiFallback](https://modernjs.dev/configure/app/tools/dev-server.html#historyapifallback) 即可解决这个问题，不过我试了下还是有问题，等我排查一下哈

**Comment by chenjiahan** [comment]
这里有问题是因为使用 htmlPlugin 修改了 HTML 文件的 filename，由于 dev server 不会直接读取 htmlPlugin 的选项，因此 dev server 不知道 HTML 的路径发生了变化。

建议改成以下写法来修改 HTML 文件的路径：

```js
export default {
  html: {
      disableHtmlFolder: true,
  },
  output: {
    distPath: {
      html: '',
    },
  }
}
```

**Comment by beilo** [comment]
@chenjiahan 这个后面会修复嘛？因为自定义htmlPlugin的filename场景还是蛮常见的。



> 这里有问题是因为使用 htmlPlugin 修改了 HTML 文件的 filename，由于 dev server 不会直接读取 htmlPlugin 的选项，因此 dev server 不知道 HTML 的路径发生了变化。
> 
> 建议改成以下写法来修改 HTML 文件的路径：
> 
> ```js
> export default {
>   html: {
>     disableHtmlFolder: true,
>   },
>   output: {
>     distPath: {
>       html: '',
>     },
>   }
> }
> ```

这个解决方案是正确的。感谢感谢

**Comment by chenjiahan** [comment]
> 因为自定义htmlPlugin的filename场景还是蛮常见的。

不太好兼容，因为 htmlPlugin 的配置可以很灵活，比如写成一个函数，或者是存在多份配置（MPA 场景）。

对于 dev server 来说蛮难兼容的，所以最好还是通过 Modern.js 的 html / output 配置来修改。

**Comment by beilo** [comment]
确实，只要注释了tools.htmlPlugin.filename,就没问题了。再次感谢大佬解答，谢谢~
