### ISSUE TITLE
[Bug]: babel插件require(require.resolve())导入的异常情况

### ISSUE THREAD

**Issue by beilo** [web-infra-dev/modern.js#4478]
### 版本信息

```sh
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 272.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @modern-js/builder: ^2.31.2 => 2.31.2 
    @modern-js/builder-webpack-provider: ^2.31.2 => 2.31.2
```

### 问题详情

```js
// 这种情况会出现以下3种异常  The given scenario may give rise to the following three anomalies:
// require(require.resolve(
//   "@dr.pogodin/babel-plugin-react-css-modules"
 )),
// 这种情况正常  This situation is considered ordinary.
'@dr.pogodin/babel-plugin-react-css-modules',
```
1. data:text/javascript,import "core-js"
需要关闭 output.polyfill: "off",
It is advisable to deactivate the "output.polyfill" by setting it to "off".
```sh
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
File: data:text/javascript,import "core-js";
Module build failed (from ./node_modules/@modern-js/builder-shared/compiled/babel-loader/index.js):
Error: [BABEL] /Users/leipeng/Desktop/codemao-leipeng/test/data:text/javascript,import "core-js";: .default is not a valid Plugin property
```

2. Error: [BABEL] /Users/leipeng/Desktop/codemao-leipeng/test/data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;: .default is not a valid Plugin property
```sh
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
Error: Child compilation failed:
  Module build failed (from ./node_modules/@modern-js/builder-shared/compiled/babel-loader/index.js):
  Error: [BABEL] /Users/leipeng/Desktop/codemao-leipeng/test/data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;: .default is not a valid Plugin property
```

### 复现链接

下面给出了最小demo
Below is a minimalistic demonstration provided:

### 复现步骤

[test.zip](https://github.com/web-infra-dev/modern.js/files/12397098/test.zip)

代码在rspack.js中
步骤：
npm i
npm start

感谢各位的帮助

The code resides within the "rspack.js" file.
Steps:
1. Execute "npm i"
2. Commence with "npm start"

Appreciation for the aid extended by all.

**Comment by chenjiahan** [comment]
以下两种写法都是支持的：

- `require.resolve("@dr.pogodin/babel-plugin-react-css-modules")`
- `@dr.pogodin/babel-plugin-react-css-modules`

以下这个写法里的 require 是多余的，因为 Babel 不支持这个写法：

`require(require.resolve("@dr.pogodin/babel-plugin-react-css-modules"))`

你可以参考一下 Babel 源代码里的类型定义，其中 PluginObj 对应的是 require 插件实例的写法，只能在非数组的情况下使用：

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/82448ee5-6794-4fc1-9e12-75350f012d10)

**Comment by beilo** [comment]
@chenjiahan 十分感谢你的解答
