### ISSUE TITLE
[Bug]: Phantom dependencies in @modern-js/plugin-garfish

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/modern.js#4505]
### Version

```sh
@modern-js/plugin-garfish latest
```

### Details

This package caused my project to contain multiple reacts. If their versions are too different like "18.2.0" and "17.0.2", It will lead to more problems.

![f3c96454-fb4b-4bd4-a380-21fec009553e](https://github.com/web-infra-dev/modern.js/assets/79413249/db327599-fa7d-4986-b236-dd236a77ed73)

In this package, dependencies "react" and "react-dom" are used, but they are not written in "package.json".

Maybe they should be written in peerDependencies

https://github.com/web-infra-dev/modern.js/blob/20447156f2955fb747799e9cda1b93469c0a9ad3/packages/runtime/plugin-garfish/src/runtime/utils/setExternal.ts#L1-L10

### Reproduce link

https://github.com/web-infra-dev/modern.js/blob/20447156f2955fb747799e9cda1b93469c0a9ad3/packages/runtime/plugin-garfish/src/runtime/utils/setExternal.ts#L1-L10

### Reproduce Steps

no need to reproduce

**Comment by chenjiahan** [comment]
PR welcome~
