### ISSUE TITLE
Feature Request: support pageExtensions and apiExtensions

### ISSUE THREAD

**Issue by tqma113** [web-infra-dev/modern.js#458]
https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions

`modern.config.js`
```js
module.exports = {
  pageExtensions: ['page.tsx', 'page.ts', 'page.jsx', 'page.js'],
  apiExtensions: ['api.tsx', 'api.ts', 'api.jsx', 'api.js'],
}
```

Only make the files with extension `page.tsx` to a page route and  the files with extension `api.tsx` to a api route.

**Comment by chenjiahan** [comment]
This issue is outdated, because we supported nested routes in Modern.js v2.
