### ISSUE TITLE
plugin-bff 和 plugin-storybook 执行了 npm run build 之后会生成 .runtime-exports 目录

### ISSUE THREAD

**Issue by leeight** [web-infra-dev/modern.js#460]
RT

**Comment by leeight** [comment]
感觉 `.runtime-exports` 的存在也是设计问题。
不清楚当时为了解决什么问题而产生的，当时有讨论过的方案有哪些？为什么最后选择了这个方案？

**Comment by chenjiahan** [comment]
这个 issue 应该可以 close 了，目前 .runtime-exports 是在 node_modules 下面，对用户无感知，主要用于存放一些框架生成的临时文件。

未来等 Rspack 支持了 virtual module，可以考虑优先使用 virtual module 来实现，避免磁盘写入行为。
