### ISSUE TITLE
Notice of breaking change in npm for packages published with provenance

### ISSUE THREAD

**Issue by feelepxyz** [web-infra-dev/modern.js#4611]
### Version

N/A

### Details

We're working on a security improvement for packages published with provenance, `@modern-js` being one such package! 🙌 

Context:

The change will start blocking publishes that come from a publishing source (e.g. repo in github) that is different from a previous version published with provenance. For example, if you move the repo for a package and you use provenance, before publishing the new version you will need to log in to your npm account and "reset" the publishing source for a given package, gated behind 2FA if configured. This will protect against long lived access token compromises taking over packages, as you will also need access to the npm account and/or the original source repo.

In an ideal world you don't even notice this until you need to transfer the package repository or want to stop publishing with provenance (which hopefully should be rare!).

Impact for `@modern-js`: Currently I can see several [test versions published without provenance for `@modern-js`](https://www.npmjs.com/package/@modern-js/rspack-generator?activeTab=versions). Doing this would result in blocked publishes for the versions without provenance unless you manually reset the publishing source, which seems very annoying at your scale.

Couple questions:
- Is this a welcome change to the security of packages published with provenance?
- Could you change your publishing workflow for test packages to always include provenance? e.g. set this up using a actions trigger
- Are these test packages published from local machines currently?

### Reproduce link

N/A

### Reproduce Steps

N/A

**Comment by caohuilin** [comment]
@feelepxyz 
Some versions without provenance were published using internal CI machines because I needed to publish these test versions to verify some internal package logic. The pipelines running these tests are not well integrated with Github, and there is also an issue with the slow speed of Github Actions, which can affect verification efficiency.

For a Monorepo repository like Modern.js, which contains over 100 npm packages, it would be very slow to force all packages to be published using Github Actions. In testing and pre-release scenarios, I believe it should not be prohibited to publish locally.

**Comment by feelepxyz** [comment]
> Some versions without provenance were published using internal CI machines because I needed to publish these test versions to verify some internal package logic. The pipelines running these tests are not well integrated with Github, and there is also an issue with the slow speed of Github Actions, which can affect verification efficiency.

Thanks for the context here, this makes sense.

> However, it would be even better if we could apply this policy specifically to stable releases, and allow local publish of pre-release versions.

This is good feedback. There's a few options here:
- Enforce all versions have provenance and if this can't be done: disable provenance for all versions 😞 
- Introduce a toggle per package for enforcing that the publishing source matches for every version if publishing with provenance (if disabled: you could still publish with provenance but get no security benefit)
- Possibly in addition to the toggle: Introduce a per package/org policy where you enforce which version ranges/tags/types must have matching publishing sources with provenance
  - Sounds like you need some version of this to get the security benefit here with your current setup
  - This is definitely the most amount of work and we'll need to think carefully about how we do this without introducing to many foot-guns, e.g. if the policy is too loose, an attacker could just publish a older version, not tagged as latest that would still be installed in lots of projects (e.g. say your package latest is v10, but most users are still requiring v9 - an attacker could then craft several backports that would probably get picked up by a lot of projects trying to find the latest v9 for example).
  - In your case, if you could write a policy that allowed something like `^0.0.0`-pre-releases only but enforced all other versions you would get the security benefit.
  - Maybe there's a simple toggle to not enforce pre-releases as these are not picked up by the npm resolver by default unless you are currently on a pre-release.

Thanks for the feedback ❤️  going to discuss this with the team.
