### ISSUE TITLE
[Feature]: rspack support source.include and source.exclude

### ISSUE THREAD

**Issue by thinkeyy** [web-infra-dev/modern.js#4618]
### 这个功能解决了什么问题？

https://github.com/web-infra-dev/rspack/issues/3067
rspack allready supported builtin:swc-loader，Whether to consider support this feature？

### 你期望的 API 是什么样子的？

source.include ； source.exclude

**Comment by chenjiahan** [comment]
Yes, we will be implementing `source.include` and `source.exclude` soon.

@9aoy Can you share the design and planning for this?

**Comment by 9aoy** [comment]
@thinkey-yang I wrote an RFC about this and we'll be putting it into development this week. https://github.com/web-infra-dev/modern.js/discussions/4620

**Comment by chenjiahan** [comment]
Supported in latest Rsbuild version: https://github.com/web-infra-dev/rsbuild

We will integrate Rsbuild to Modern.js in a few weeks.

**Comment by thinkeyy** [comment]
so, Modern.js Builder no longer maintains rspack

**Comment by chenjiahan** [comment]
Modern.js Builder is renamed to Rsbuild, you can think of it as the next version of Modern.js Builder.
