### ISSUE TITLE
[Bug]: strange error when updating the file and dev server fails to refresh (react-i18next)

### ISSUE THREAD

**Issue by AsuraKev** [web-infra-dev/modern.js#4693]
### Version

```sh
chrome, modern.js latest, rspack
```

### Details

I am using react-i18next for translation, I am making some small update on my tsx file to change translation key but the dev server fails to refresh page with the updated changes

![image](https://github.com/web-infra-dev/modern.js/assets/52765572/5248d755-606a-42cc-bcea-fd7df0fc107c)

### Reproduce link

no link available

### Reproduce Steps

1. Install react-i18next and i18next 
2. Setup translation
3. live update the code to see changes
4. error occurs

**Comment by chenjiahan** [comment]
This looks like an exception thrown by Rspack, you can open an issue in the Rspack repo,  or close it if the problem has been solved.
