### ISSUE TITLE
[Bug]: 在windows环境下，使用dev.proxy出错

### ISSUE THREAD

**Issue by ubbcou** [web-infra-dev/modern.js#4696]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 17.98 GB / 31.92 GB
  Browsers:
    Chrome: 116.0.5845.188
    Edge: Chromium (117.0.2045.31)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @modern-js/builder-rspack-provider: 2.35.0 => 2.35.0
    @modern-js/eslint-config: 2.35.0 => 2.35.0
    @modern-js/monorepo-tools: 2.35.0 => 2.35.0
    @modern-js/tsconfig: 2.35.0 => 2.35.0
```

### 问题详情

在 windows 环境下，新创建的 modern.js 项目，加入 api.proxy 选项后，出现两个异常：
1. 在终端中，始终循环报错 “'networksetup' is not recognized as an internal or external command,
operable program or batch file.” 。通过 ctrl + c 可以停止 web server 但是无法停止这个报错，除非结束终端。
2. 我使用 vscode 编辑器，在循环报错时，vscode始终循环自动打开并聚焦在 ....\node_modules\whistle\bin\whistle.js 文件

![image](https://github.com/web-infra-dev/modern.js/assets/25863414/6d755ec2-47c1-4665-81dd-9c82ce6c6cf6)

我的 modern.config.ts

```
import { appTools, defineConfig } from '@modern-js/app-tools';
import { proxyPlugin } from '@modern-js/plugin-proxy';

// https://modernjs.dev/en/configure/app/usage
export default defineConfig<'rspack'>({
  runtime: {
    router: true,
  },
  plugins: [appTools(), proxyPlugin()],
  dev: {
    proxy: {},
  },
});
```

### 复现链接

https://github.com/ubbcou/modern.js-bug-report

### 复现步骤

1. 在 windows 环境下
2. 执行 `pnpm dev`
3. 控制台报错 'networksetup' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chenjiahan** [comment]
这应该是一个 bug，Proxy 插件使用了 networksetup 命令，但 Windows 系统下没有 networksetup 命令，所以会出现问题。

后续我们看下怎么修复这个问题

**Comment by chenjiahan** [comment]
Fixed in https://github.com/web-infra-dev/modern.js/pull/4700
