### ISSUE TITLE
[Bug]: Two output files share the same path when use CSS modules

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/modern.js#4711]
### Version

```sh
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 342.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
  npmPackages:
    @modern-js/eslint-config: 2.33.1 => 2.33.1 
    @modern-js/module-tools: 2.33.1 => 2.33.1 
    @modern-js/tsconfig: 2.33.1 => 2.33.1
```

### Details

The compiled CSS module filename may be same as another files.

For example, we have two files:

- /index.ts
- /index.css

Then we use `autoModules` to make `index.css` as a CSS module file.

```ts
import { moduleTools, defineConfig } from '@modern-js/module-tools';

export default defineConfig({
  plugins: [moduleTools()],
  buildConfig: {
    buildType: 'bundleless',
    style: {
      autoModules: /\.css$/,
    },
  },
});
```

Run build command, the build will fail:

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/05ba4845-a2ae-4084-ae1b-405e4da6973b)

### Reproduce link

https://github.com/chenjiahan/modern-module-css-modules-name-issue

### Reproduce Steps

1. pnpm i
2. pnpm build

**Comment by 10Derozan** [comment]
Maybe you should change the filename..
Or What is the expected output?

**Comment by chenjiahan** [comment]
The expect behavior is that `index.ts` and `index.css` can work together.

We can rename the generated js file of `index.css` by adding a special suffix, so it will not conflict with `index.ts`.

**Comment by 10Derozan** [comment]
I'll save the filename, and replace `.` with `_`, so `index.css` will be `index_css.js`. How about it

**Comment by 10Derozan** [comment]
but `index.module.css` will be `index_module_css.js`, but now it is `index_module.js`

**Comment by chenjiahan** [comment]
This looks good:
- `index.css` -> `index_css.js`
- `index.module.css` -> `index_module_css.js`

Maybe this is even more safer:

- `index.css` -> `__index_css.js` or `$index_css.js`
