### ISSUE TITLE
[Feature]: Add a CI to detect duplicate dependencies

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/modern.js#4714]
### What problem does this feature solve?

Related issue: https://github.com/web-infra-dev/modern.js/issues/494

### What does the proposed API look like?

If we can add a CI to detect duplicate dependencies, it will help us to unify the version of 3rd party dependencies and reduce duplicate dependencies.

**Comment by tunahan-guler** [comment]
bro how can we reduce duplicate dependencies now?

**Comment by chenjiahan** [comment]
@tunahan-guler This issue is about the duplicate package problem in this modern.js repository.

Can you describe the problem you are currently facing?

**Comment by tunahan-guler** [comment]
@chenjiahan  I use my own library in my main project and subproject. I didn't add these as shared. I wonder if this will cause a problem.

**Comment by chenjiahan** [comment]
I understand that your topic may not be in line with our current discussion. To manage shared dependencies, you should take care of this aspect yourself. You can explore options such as the pnpm workspace or any other suitable alternative.

**Comment by chenjiahan** [comment]
https://github.com/bmish/check-dependency-version-consistency is a suitable tool
