### ISSUE TITLE
[Feature]: Discontinue direct PR from web-infra-dev/modern.js

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/modern.js#4766]
### What problem does this feature solve?

At present, any member of the web-infra-dev organization can push a branch directly to the web-infra-dev/modern.js, facilitating easy collaboration. However, I propose disabling this method of direct merging. Instead, I suggest almost contributors should fork the repository and submit changes via a PR. This approach could lead to a cleaner branch structure in the master repository.

### What does the proposed API look like?

nothing

**Comment by chenjiahan** [comment]
Does GitHub provide a switch to control this?

**Comment by chenjiahan** [comment]
Sometimes we need to push a branch to the main repository, for example, when we release the canary version via actions.

**Comment by bvanjoi** [comment]
> Sometimes we need to push a branch to the main repository, for example, when we release the canary version via actions.

This would be an infrequent operation for most contributors, and we can assign additional permissions to those who require them.

**Comment by chenjiahan** [comment]
The members of web infra org can push to this repo and release canary version. Community contributors need to fork this repo to submit a PR.

This is a common approach on GitHub and it allows us to limit the branch numbers of the main repo.
