### ISSUE TITLE
[Bug]: Hot Reload is not working in mfe app when use router

### ISSUE THREAD

**Issue by tunahan-guler** [web-infra-dev/modern.js#4776]
### Version

```sh
2.35.1
```

### Details

I am using microfrontend features in modern.js. Hot reload is working when i am not using React router. But when i add react router(@modern-js/runtime/router) hot reload is not working.

### Reproduce link

.

### Reproduce Steps

.

**Comment by chenjiahan** [comment]
Can you provide a reproduce repo for this?

**Comment by chenjiahan** [comment]
This issue will be closed. Feel free to comment and reopen it if you have any further questions.
