### ISSUE TITLE
Does the coverage test truly provide help?

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/modern.js#4780]
### Version

```sh
nothing
```

### Details

After reviewing this [comment](https://github.com/web-infra-dev/modern.js/pull/4775#issuecomment-1757374793), I am skeptical about the real benefit of this coverage for our testing.

I also noticed several potential issues:
- We are using ﻿`vitest` and `﻿jest` concurrently, and `﻿vitest` by default employs ﻿`c8` to generate coverage, which is not as precise as the ﻿babel coverage used by ﻿`jest`.
- Can the coverage report genuinely assist us in identifying bugs we've overlooked? I believe for most scenarios, simply adding relevant tests should be sufficient.

### Reproduce link

nothing

### Reproduce Steps

nothing

**Comment by chenjiahan** [comment]
I have the same opinion as you, the coverage is inaccurate and probably useless now.

Our tests include Jest UT, Vitest UT, Jest E2E and Playwright E2E, each using separate coverage reports. In my daily development, the coverage reports are often of no use.

If disabling coverage can improve the test performance, we can consider changing it.

**Comment by chenjiahan** [comment]
Also, based on my experience in other projects, Vitest should use Istanbul to provide more accurate coverage.
