### ISSUE TITLE
[Bug]: do we need `test:watch`?

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/modern.js#4810]
### Version

```sh
nothing
```

### Details

In my opinion, ﻿`test:watch` is a rather uncommon script. Most developers prefer to modify the source file and then run tests, rather than developing while simultaneously monitoring test results.

### Reproduce link

nothing

### Reproduce Steps

nothing

**Comment by chenjiahan** [comment]
`test:watch` is very useful, and Vitest even uses watch mode by default: https://vitest.dev/guide/cli.html
