### ISSUE TITLE
[Feature]: Which test toolkit do you prefer?

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/modern.js#4829]
### What problem does this feature solve?

We currently have four testing toolkits at our disposal: `﻿vitest`, `﻿jest`, `puppeteer` and `﻿playwright`. However, it's not necessary to use all of these toolkits simultaneously.

I lean towards using ﻿`jest` in combination with `﻿playwright` (I even believe that just using ﻿`playwright` might be sufficient). What are your thoughts on this?

### What does the proposed API look like?

nothing

**Comment by chenjiahan** [comment]
Playwright is not designed for unit testing, so we still need Jest.

And Vitest can be removed from the modern.js codebase, as the Modern.js Builder is being moved to the Rsbuild repo, and most other packages uses Jest for ut.
