### ISSUE TITLE
[Bug]: Modern build failed when the buildPreset is npm component

### ISSUE THREAD

**Issue by fengjiling123** [web-infra-dev/modern.js#4900]
### 版本信息

```sh
system： windows11
version: 2.34.0
pnpm version: 8.9.2
node version: 16.16.0
```

### 问题详情

![image](https://github.com/web-infra-dev/modern.js/assets/31927435/50e53ab8-4dc3-44b1-bc25-11d387f7bc37)

### 复现链接

https://github.com/web-infra-dev/modern-js-examples

### 复现步骤

1.下载[modern-js-examples](https://github.com/web-infra-dev/modern-js-examples)
2.到basic-module下，将buildPreset改成npm-component
3.pnpm build 之后报错

**Comment by HerringtonDarkholme** [comment]
Hi, can you try  these commands in a **new** project?  https://ast-grep.github.io/guide/api-usage.html

```bash
pnpm add @ast-grep/napi
```

```js
import { js } from '@ast-grep/napi';

const source = `console.log("hello world")`
const ast = js.parse(source)
const node = ast.root().find('console.log')
```

If the code example works, I would speculate the problem is pnpm.

**Comment by HerringtonDarkholme** [comment]
Can you list the content inside node_modules of https://github.com/ast-grep. Probably we need all directories inside there.

Example screenshot

![image](https://github.com/web-infra-dev/modern.js/assets/2883231/833864f6-4a98-43f6-a934-de301955219c)

**Comment by fengjiling123** [comment]
![image](https://github.com/web-infra-dev/modern.js/assets/31927435/96a9176b-13e2-4cd8-8b3d-181402ba071f)

**Comment by HerringtonDarkholme** [comment]
> This example also throws the same error.

Can you try listing the files under node_modules? Especially `@ast-grep`.

**Comment by HerringtonDarkholme** [comment]
I noticed you are using MinGW, can you try it without using MinGW?

**Comment by 10Derozan** [comment]
If there are no other issues, this will be closed. @fengjiling123
