### ISSUE TITLE
[Feature]: simplify output logs in integration tests

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/modern.js#4906]
### What problem does this feature solve?

There are too many log outputs in the integration test, and it is difficult to locate the actual error case information.

for example, it is difficult to locate the actual error location of this test：
https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/6740600034/job/18323917427

- This error often appears, but it has no impact on the actual test. Can it be fixed or hidden?
<img width="1456" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/22373761/1dedccf9-e429-45bf-a982-f8475189c5cf">

- This is an expected output. Can this log not be displayed?
<img width="1337" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/22373761/e9b37424-f89b-4211-b9ee-1c25f7806723">

### What does the proposed API look like?

none

**Comment by Timeless0911** [comment]
Maybe we can set 
`
// jest.spyOn(process.stdout, 'write').mockImplementation(jest.fn());// jest.spyOn(process.stderr, 'write').mockImplementation(jest.fn());
`
