### ISSUE TITLE
[Feature]: iife format type no bundle name config ？

### ISSUE THREAD

**Issue by FeSeason** [web-infra-dev/modern.js#4912]
### What problem does this feature solve?

use iife format type,  but no output library name config.

### What does the proposed API look like?

hope api config  such as [name] config in buildConfig:

```
{
      format: 'iife',
      target: 'es6',
      outDir: './dist/iife',
      name: 'appLibName',
},
```

**Comment by 10Derozan** [comment]
You can use [global-name](https://esbuild.github.io/api/#global-name) by [esbuildOptions](http://modernjs.dev/module-tools/api/config/build-config.html#esbuildoptions)
