### ISSUE TITLE
[Feature]: 路由分组 (Route Group)

### ISSUE THREAD

**Issue by WinmezzZ** [web-infra-dev/modern.js#4956]
### What problem does this feature solve?

希望提供一个路由分组的功能

很多路由模块都有一个归属，因此可能会放在同一个文件夹中，但是这个上层文件夹并不想占用路由路径。

比如登录，注册，找回密码，这些都可以归类到 auth 分类，按照目前的做法就是放在 routes/auth/xx目录中。但是依然想使用一级路由 /signIn /signUp，好像就没办法了。

在nextjs 13 app router 中有类似的解决方案，使用`()` 小括号的文件夹则为路由分组

```
(auth)
|  signIn
|  |  page.tsx
|  signUp
|  |  page.tsx
```

这样就不会导致想更多使用一级路由而导致routes下一级文件非常多的情况，便于管理分组了

### What does the proposed API look like?

`(group-name)` 的路由文件夹名称则为路由分组

**Comment by KyrieLii** [comment]
这个吗 [无路径布局](https://modernjs.dev/guides/basic-features/routes.html#%E6%97%A0%E8%B7%AF%E5%BE%84%E5%B8%83%E5%B1%80)

**Comment by WinmezzZ** [comment]
哈哈是的，搜了下分组相关字段没搜到~

小建议，可以在这里添加 `分组` 相关字眼，利于用户识别和理解，无路径布局有点难懂

`无路径布局/路由分组`

**Comment by KyrieLii** [comment]
@WinmezzZ 感谢反馈，我们会优化下文档措辞，当然也欢迎 PR 😊

**Comment by WinmezzZ** [comment]
已创建pr
