### ISSUE TITLE
[Feature]: Support running individual tests in vscode

### ISSUE THREAD

**Issue by wangjue666** [web-infra-dev/modern.js#5043]
### What problem does this feature solve?

我想在 `vscode` 中只执行单个测试用例

![image](https://github.com/web-infra-dev/modern.js/assets/24707417/98fa1c26-6886-4e6d-885d-bb75f3c91726)

我看到 `@modern-js/plugin-testing` 这个包依赖的是`jest`来进行处理的，但是直接点会出错，提示找不到 `jest`, 我把jest下载到依赖里头，再点击运行提示

```
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.     
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    E:\clone\amazon-spider-tools\packages\utils\tests\toolKit\extractNumbers.test.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { extractNumbers } from '@/toolKit/extractNumbers';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1505:14)
```

看起来像是配置上的问题，但是直接运行 `modern test` 是没有问题的。

文档上也没有提及到

![image](https://github.com/web-infra-dev/modern.js/assets/24707417/a89ee245-08d5-444d-ace0-03616a496b11)

想请教下, 有什么简易的方法可以做到吗？

另：modern.js 这个工具对我而言非常好用, 帮助了我很大的忙，非常感谢你们的付出！

### What does the proposed API look like?

希望可以简易的实现在vscode运行单个测试用例， 并完善文档部分

**Comment by chenjiahan** [comment]
感谢支持 🙏

在 VS Code 中运行单个测试用例应该是由 [Jest Runner](https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner) 支持的。

由于 Modern.js 的 test 命令是基于 Jest 封装的，你可以添加自定义配置，来支持启动 Modern.js test 来运行单个测试用例。

参考 VS Code 插件文档里的 create-react-app 的例子：

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/fe8fcbaf-f215-4e7b-af8c-1d9bcf196fd5)

**Comment by chenjiahan** [comment]
我试了下在 `.vscode/settings.json` 添加以下内容就可以了：

```json
{
  "jestrunner.jestCommand": "npm run test --",
  "jestrunner.debugOptions": {
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/modern",
    "runtimeArgs": [
      "test",
      "${fileBasename}",
      "--runInBand",
      "--no-cache",
      "--watchAll=false",
      "--color"
    ]
  }
}
```

![image](https://github.com/web-infra-dev/modern.js/assets/7237365/05c00a4e-e7f2-4039-bac0-76ec6464ec9c)

**Comment by wangjue666** [comment]
@chenjiahan  感谢❤️！，但是这样写在`monorepo`架构下还是有些问题， 需要想办法先切换到` packages/子项目/` 下， 再执行测试指令， 我先去看看`Jest Runner` 的文档！

**Comment by wangjue666** [comment]
> @chenjiahan 感谢❤️！，但是这样写在`monorepo`架构下还是有些问题， 需要想办法先切换到` packages/子项目/` 下， 再执行测试指令， 我先去看看`Jest Runner` 的文档！

有个 ` "jestrunner.projectPath": "packages/子项目",` 这样的配置，但是它好像只能写死路径，没办法自动切换到对应的子项目下，或者把工作区自动设定到我当前的点击的文件下，当然这也是 `jestrunner`的**问题** https://github.com/firsttris/vscode-jest-runner/issues/340     翻阅了一下它相关的issues, 好像没有好的解决方案.

**Comment by chenjiahan** [comment]
了解，那可以在 jest runner 仓库那边讨论下这个问题
