### ISSUE TITLE
[Feature]: support `split-by-module` chunk split strategy when use rspack

### ISSUE THREAD

**Issue by SyMind** [web-infra-dev/modern.js#5054]
### What problem does this feature solve?

Added in rspack 0.4.1 is support function type for `splitChunks.{cacheGroup}.{test, name}`. So we can support `split-by-module` chunk split strategy in modern.js when use rspack.

More details can be found in the: https://github.com/web-infra-dev/rspack/releases/tag/v0.4.1

### What does the proposed API look like?

```js
performance: {
  chunkSplit: {
    strategy: 'split-by-module',
  },
},
```

**Comment by SyMind** [comment]
@chenjiahan Since my project encompasses this area, I would be willing to tackle this issue within the week if you're agreeable.

**Comment by chenjiahan** [comment]
That will be great! I will assign this issue to you 😄
