### ISSUE TITLE
[Feature]: Add option to only copy files

### ISSUE THREAD

**Issue by meesvandongen** [web-infra-dev/modern.js#5105]
### 这个功能解决了什么问题？

Currently, when specifying `copy`, I also get an `index.js` file that is compiled.

I am using the bundleless method for my other build configs, and they are in a subfolder.
```ts
buildConfig: [
  {
    format: "cjs",
    target: "es6",
    buildType: "bundleless",
    outDir: "./dist/lib",
    dts: false,
  },
  {
    format: "esm",
    target: "es6",
    buildType: "bundleless",
    outDir: "./dist/es",
    dts: false,
  },
  {
    outDir: "./dist/types",
    dts: {
      only: true,
    },
  },
]
```

In my case, I also want to copy files from my public folder (my use case is fonts). So I initially added this:
```ts
{
  copy: {
    patterns: [
      {
        from: "./**/*",
        to: "./",
        context: "./public",
      },
    ],
  },
},
```

This however also uses the defaults to create a bundle of `index.js`. I did find a workaround:
```ts
{
  buildType: "bundleless",
  dts: false,
  input: [],
  copy: {
    patterns: [
      {
        from: "./**/*",
        to: "./",
        context: "./public",
      },
    ],
  },
},
```
As you can see, you can set `input` to an empty array to only copy files. This however requires the `buildType` to be `bundleless`, since the `bundle` `buildType` doesn't allow an empty array. Then, `dts` must be set to `false` to stop generating typings in the dist folder.

### 你期望的 API 是什么样子的？

My proposal is to have a more ergonomic API for disabling the build step (and only having a copy step). This could be `"buildType": "none"`. Alternatively, similar to `dts`, `copy` could also have an option `"only": true`.

If this is undesirable, the documentation might be updated to reflect this use case. 

If that is also undesirable, I hope this github issue allows for some documentation on the matter to those who need it as all the APIs for a workaround are already in place.

**Comment by 10Derozan** [comment]
Thank you for suggestions! I have improve it in https://github.com/web-infra-dev/modern.js/pull/5226
Now you only need to set `input: []`, we will skip the compilation.

**Comment by 10Derozan** [comment]
I am sorry that I see the issue util totay. If you still have any question, you can @me or contact me by email, I will support you directly.
