### ISSUE TITLE
[Feature]: bundleless模式下，希望为src每个ts生成单独的d.ts，并且以文件夹形式输出demo/(index.js + index.d.ts)

### ISSUE THREAD

**Issue by lemondreamtobe** [web-infra-dev/modern.js#5158]
### 这个功能解决了什么问题？

解决es模块导入时，类型声明显示

### 你期望的 API 是什么样子的？

```
 format: 'esm',
            target: 'es6',
            outDir: './es',
            idDir: true,
            dts: true,
            transformLodash: true,
            buildType: 'bundleless'
```

**Comment by 10Derozan** [comment]
According to your configure, you will get a output chunk like es/xx/index.js, es/xx/index.d.ts.
It is not your needs?

**Comment by 10Derozan** [comment]
I am sorry that I see the issue util totay. If you still have any question, you can @10Derozan or contact me by email, I will support you directly.

**Comment by kirainmoe** [comment]
For those who are facing the same problem (`modern build` does not generate .d.ts in bundless mode for sometimes), try to set `incremental: false` in tsconfig.json will solve the problem.

**Comment by 10Derozan** [comment]
Any update? Please reopen it if you have any questions.

**Comment by 10Derozan** [comment]
> For those who are facing the same problem (`modern build` does not generate .d.ts for every .ts files in bundless mode for sometimes), try to set `incremental: false` in tsconfig.json solves for me.

Yes, when enable incremental, it will generate tsbuildinfo. When rebuild, modern will clean dist but not clean tsbuildinfo, so `d.ts` will not be generated again. If you want to enable incremental, please use https://modernjs.dev/module-tools/api/config/build-config.html#dtsenabletscbuild

**Comment by lemondreamtobe** [comment]
sorry, i did not review this issue for long time.

**Comment by lemondreamtobe** [comment]
but i had really resolved this problem well.
firstly, i set `incremental: false` in my `tsconfig.json`
secondly, i modified dts config in `modern.config.js`
```
 dts: {
     tsconfigPath: './tsconfig.json'
 }
```
it work well for me~

**Comment by 10Derozan** [comment]
fine

> but i had really resolved this problem well. firstly, i set `incremental: false` in my `tsconfig.json` secondly, i modified dts config in `modern.config.js`
> 
> ```
>  dts: {
>      tsconfigPath: './tsconfig.json'
>  }
> ```
> 
> it work well for me~
