### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'getFullText')

### ISSUE THREAD

**Issue by CsongL** [web-infra-dev/modern.js#5196]
### Version

```sh
System: Mac
Node version: v18.16.1
Npm version: v9.5.1

@modern-js/builder-rspack-provider: "2.35.0",
```

### Details

通过 emo start方式启动项目时，有相应的报错，具体的报错信息如下：
<img width="1568" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/30070610/c26d3108-c770-439e-a0e6-1490aea6424d">

### Reproduce link

无

### Reproduce Steps

无

**Comment by chenjiahan** [comment]
哈喽，上面提供的信息无法直接定位问题，能够通过以下方式提供一个复现呢：

1. 提供一个 GitHub 可访问的复现仓库地址
2. 在内部发起 OnCall，提供一个可复现问题的 Cloud IDE 地址

**Comment by CsongL** [comment]
谢谢您的回复，想再请教一下，就是内部发起OnCall的话，是在下面这个群里进行oncall 嘛，感谢～
<img width="323" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/30070610/2076041c-d450-4b64-a465-b33c4e2eb0fb">

**Comment by chenjiahan** [comment]
嗯嗯，是的

**Comment by 10Derozan** [comment]
It has been fixed in #5199
