### ISSUE TITLE
[Bug]: dep isBot@^4 needs node >= 18

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/modern.js#5205]
### Version

```sh
-
```

### Details

Ref: https://github.com/web-infra-dev/modern.js/pull/5186
Maybe we need to downgrade it to ^3.

### Reproduce link

-

### Reproduce Steps

-

**Comment by KyrieLii** [comment]
cc @GiveMe-A-Name

**Comment by GiveMe-A-Name** [comment]
Yes,it's my mistake. We need downgrade it to ^3

**Comment by GiveMe-A-Name** [comment]
It fixed by https://github.com/web-infra-dev/modern.js/pull/5206
