### ISSUE TITLE
[Bug]: Can't use tailwindcss in the Rspress demo page.

### ISSUE THREAD

**Issue by veaba** [web-infra-dev/modern.js#5215]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
```

### Details

Can't use tailwindcss in the Rspress demo page.

![vite-dist](https://github.com/web-infra-dev/modern.js/assets/8652596/a87431f8-70f0-4cd6-944c-14c6b538f7cd)

more details see: <https://github.com/veaba/modern-rspress-component>

### Reproduce link

https://github.com/veaba/modern-rspress-component

### Reproduce Steps

1. modern dev
```bash
pnpm run install
pnpm run dev
```

2. vite dev
```bash
pnpm run build
pnpm run dev-vite

```

**Comment by 10Derozan** [comment]
Maybe you need configure tailwind, this is the usage problem.
For example, I use `h-12`, it exists and  takes effect.
![image](https://github.com/web-infra-dev/modern.js/assets/50694858/df25863b-2ad3-419e-bfdf-10321a29db82)
