### ISSUE TITLE
[Bug]: Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir ...

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/modern.js#5227]
### Version

```sh
"@rspack/core": "0.5.0-canary-75e6335-20240115063516"
```

### Details

print Watchpack Error when run dev in rspack 0.5.0-canary:

<img width="748" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/22373761/0897f9d7-1095-4f94-88e2-c6fe38f8872e">

### Reproduce link

https://github.com/web-infra-dev/modern.js/tree/reproduce-0115-error

### Reproduce Steps

1. pnpm i
2. cd tests/integration/bff-express
3. DEBUG=builder pnpm dev

**Comment by h-a-n-a** [comment]
This is an issue related to missing dependencies. The following missing dependency is returned to watchpack, causing the directory watcher failed to watch based on its 'dirname' which is 'modern.js/packages/toolkit/runtime-utils/dist/cjs/node/index.js' in this case which is a file.

```
modern.js/packages/toolkit/runtime-utils/dist/cjs/node/index.js/router.js
```

**Comment by Boshen** [comment]
I managed to reproduce the issue.

There's a alias

```
'@modern-js/runtime-utils/node$': '/Users/bytedance/github/modern.js/packages/toolkit/runtime-utils/dist/cjs/node/index.js',
```

for which resolving `@modern-js/runtime-utils/node/router` by passed the `$` match. enhanced-resolve did not have any test cases for this kind of resolution so I missed it.
