### ISSUE TITLE
Include microfrontend using Module federation usage in Modern Js documentation site

### ISSUE THREAD

**Issue by AsuraKev** [web-infra-dev/modern.js#5276]
### What problem does this feature solve?

Module federation v1.0 has been included in rspack. it ll be great to see how we can build microfrontend using Modern Js and module federation :)

### What does the proposed API look like?

NA

**Comment by zllkjc** [comment]
https://module-federation.io/zh/guide/framework/modernjs.html
here are some docs in module federation website about how to use with modern.js, and we will add it in modern.js website
