### ISSUE TITLE
[Bug]: @modern-js/module-tools 开发组件库，热更新太卡

### ISSUE THREAD

**Issue by GuoYiJi** [web-infra-dev/modern.js#5292]
### 版本信息

```sh
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 87.83 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 17.2.1
  npmPackages:
    @modern-js/eslint-config: 2.35.1 => 2.35.1
    @modern-js/module-tools: 2.35.1 => 2.35.1
    @modern-js/tsconfig: 2.35.1 => 2.35.1
```

### 问题详情

使用 @modern-js/module-tools 本地开发组件库的时候，每次更改代码保存 rebuild 的时候，都会耗尽 cpu 造成机器卡顿，如 vscode 卡死，可以观察下 vscode 反应跟底部 cpu 占用面板，请问那边项目文件多有遇到么，非常影响效率，请帮忙看下🙏

配置
```javascript
import { moduleTools, defineConfig } from '@modern-js/module-tools';

export default defineConfig({
  plugins: [moduleTools()],
  buildPreset({ preset }) {
    const { NPM_COMPONENT } = preset;
    return NPM_COMPONENT.filter(e => e.format !== 'cjs').map(config => {
      config.define = {
        VERSION: '1.0.1',
      };
      return config;
    });
  },
  buildConfig: {
    asset: {
      svgr: true,
    },
    alias: {
      '@': './src',
    },
    style: {
      sass: {
        additionalData: `
          @use "@/styles/variables.scss" as *;
          @use "@/styles/mixins.scss" as *;
        `,
      },
    },
  },
});

```

录屏链接：https://www.zhihu.com/zvideo/1733153234569715712

### 复现链接

#

### 复现步骤

#

**Comment by 10Derozan** [comment]
Ideally, we should only enable one watcher.
By the way, no much this feedback about this problem.

**Comment by GuoYiJi** [comment]
> 您可以尝试禁用某些任务吗？可能是存在多个watcher，占用内存过多。仅 删除esbuild 任务或 tsc 任务。您可以尝试取消某些任务吗？可能存在多个watcher，占用内存过多。删除并仅删除一个esbuild任务或tsc任务。关闭

只保留 esm 可以解决，问题出在最后一个任务，这个任务主要用来构建 typeing？我使用 esm 的模块并修改 dts 配置也可以输出 typeing

```javascript
[
  {
    format: 'cjs',
    target: 'es6',
    buildType: 'bundleless',
    outDir: './dist/lib',
    dts: false,
  },
  {
    format: 'esm',
    target: 'es6',
    buildType: 'bundleless',
    outDir: './dist/es',
    dts: false,
  },
  {
    buildType: 'bundleless',
    outDir: './dist/types',
    dts: { only: true },
  },
]
```

**Comment by GuoYiJi** [comment]
> > 您可以尝试禁用某些任务吗？可能是存在多个watcher，占用内存过多。仅 删除esbuild 任务或 tsc 任务。您可以尝试取消某些任务吗？可能存在多个watcher，占用内存过多。删除并仅删除一个esbuild任务或tsc任务。关闭
> 
> 只保留 esm 可以解决，问题出在最后一个任务，这个任务主要用来构建 typeing？我使用 esm 的任务并修改 dts 配置也可以输出 typeing
> 
> ```js
> [
>   {
>     format: 'cjs',
>     target: 'es6',
>     buildType: 'bundleless',
>     outDir: './dist/lib',
>     dts: false,
>   },
>   {
>     format: 'esm',
>     target: 'es6',
>     buildType: 'bundleless',
>     outDir: './dist/es',
>     dts: false,
>   },
>   {
>     buildType: 'bundleless',
>     outDir: './dist/types',
>     dts: { only: true },
>   },
> ]
> ```

抱歉，看错了，ems 的 dts 设置 { only: true } 后，只会输出 typeing，没有构建的 js

**Comment by 10Derozan** [comment]
只跑输出类型的任务会卡吗，如果会的话那和 tsc 有关

**Comment by GuoYiJi** [comment]
> 只跑输出类型的任务会卡吗，如果会的话那和 tsc 有关

确实是，测试了下只跑这个任务就会卡

**Comment by 10Derozan** [comment]
tsc watch 的问题可以再研究一下，对于 module tools 本身或许可以细粒度划分一下 watch 命令，只 watch 某个或者某几个任务

**Comment by FeSeason** [comment]
> Ideally, we should only enable one watcher and rebuild the all task, we need improve it next major version. By the way, no much this feedback about this problem.

+1

**Comment by FeSeason** [comment]
是否可以开发watch相关的钩子 做一些自定义的操作

**Comment by 10Derozan** [comment]
> 是否可以开发watch相关的钩子 做一些自定义的操作

欢迎直接贡献代码
