### ISSUE TITLE
[Feature]: 加一下已有插件列表以及介绍如何使用

### ISSUE THREAD

**Issue by cnyballk** [web-infra-dev/modern.js#5306]
### 这个功能解决了什么问题？

本来想用i18n插件，但是官网搜不到，npm也是跳转到官网，run new 也没有i18n的选项，实在难受

### 你期望的 API 是什么样子的？

无

**Comment by a145789** [comment]
借这个 issues 问下，看到文档里介绍无法添加webpack插件，是指和webpack插件不兼容么？那有没有什么可以平滑兼容的方案？

**Comment by chenjiahan** [comment]
@a145789 具体是哪里的文档呢

**Comment by a145789** [comment]
![image](https://github.com/web-infra-dev/modern.js/assets/37403253/06b434ad-a85f-4747-aee7-093bf1368214)

**Comment by chenjiahan** [comment]
@a145789 这里介绍的不是很完整，Modern.js 是支持注册 Webpack 插件的，需要通过 tools.webpack 字段来注册，在配置项文档里有完整介绍：https://modernjs.dev/configure/app/plugins.html

**Comment by lvscar** [comment]
> ### 这个功能解决了什么问题？
> 
> 本来想用i18n插件，但是官网搜不到，npm也是跳转到官网，run new 也没有i18n的选项，实在难受
> ### 你期望的 API 是什么样子的？
> 
> 无

我昨天也碰到了同样的情况， 最后用  i18next react-i18next i18next-http-backend i18next-browser-languagedetector 这一套在 modernJS 环境里跑起来了（客户端渲染环境OK)。  i18n 初始环境在  modern.runtime.js 文件引入。

**Comment by zllkjc** [comment]
@lvscar Modern.js 没有提供国际化的能力，推荐就是用 i18next 直接搭建，或许希望我们提供一个 i18n 的 Demo ？

**Comment by lvscar** [comment]
> [@lvscar](https://github.com/lvscar) Modern.js 没有提供国际化的能力，推荐就是用 i18next 直接搭建，或许希望我们提供一个 i18n 的 Demo ？

i18next & react-i18next  方案在 SSR / SSG 环境下没能跑起来。 我结合 Modern.js  动态路由 和 data loader 实现了一套复用 i18next json文件的 SSR/SSG 环境 i18n 方案。

routes/[lang]/page.data.js

```
import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import path from 'path';

const supportedLanguages = ['en', 'zh']

export const loader = async ({ params  }) => {
  const { lang } = params;
  if (supportedLanguages.includes(lang)){
    let filePath
    if (process.env.NODE_ENV === 'development') {
      filePath = path.join(process.cwd(), `config/public/locales/${lang}/translation.json`);
    }else{
      filePath = path.join(process.cwd(), `public/locales/${lang}/translation.json`);
    }
    const data = await readFile(filePath, 'utf8');
    const jsonData = JSON.parse(data);
    return {translation:jsonData};    
  }else{
    throw new Response('not support', { status: 404 });    
  }
};
```

在组件中
```
import { useLoaderData } from '@modern-js/runtime/router';

function createTranslator(dictionaries) {
  const dict = dictionaries || {};
  function t(key) {
    return dict[key] || key;
  }
  return { t };
}
const { translation } = useLoaderData() ;
const { t } = createTranslator(translation);  
```

然后就能以  i18next  一致的方法在 SSR / SSG 环境中使用啦。
```
<div>
{t('welcome')}
</div>
```

感谢你们的创造， Modern.js 太好用啦。
