### ISSUE TITLE
[Feature]: including antd one time. we can use the libarary anywhere.

### ISSUE THREAD

**Issue by NieShiyi** [web-infra-dev/modern.js#5407]
### What problem does this feature solve?

I use antd everywhere including many programs in apps and packages. I will install antd everywhere that leadding to a problem of different antd versions. or exporting all antd components after installing in some package.

### What does the proposed API look like?

we can install antd directly in global environment.  and use it anywhere.

**Comment by chenjiahan** [comment]
You can use alias to force all antd resolved to a single version:

https://modernjs.dev/en/configure/app/source/alias.html
