### ISSUE TITLE
[Bug]: storybook support

### ISSUE THREAD

**Issue by martin-repta** [web-infra-dev/modern.js#5460]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 PRO 6850U with Radeon Graphics     
    Memory: 5.57 GB / 27.77 GB
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @modern-js/app-tools: 2.47.1 => 2.47.1 
    @modern-js/eslint-config: 2.47.1 => 2.47.1 
    @modern-js/plugin-tailwindcss: 2.47.1 => 2.47.1 
    @modern-js/runtime: 2.47.1 => 2.47.1 
    @modern-js/tsconfig: 2.47.1 => 2.47.1
```

### Details

I have created a simple app with aim to use storybook in combination with rspack.

<img width="375" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/30607967/f0cc3dd3-6a90-46bb-bb4f-fd22119b90aa">

I am trying to enable storybook as per [instructions here](https://modernjs.dev/builder/en/guide/advanced/storybook.html#quick-start).

<img width="449" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/30607967/73f06ab9-43cf-4436-90bd-d9575a0180e6">

The problem is, that running `npx modern new` does not offer option to enable storybook

<img width="356" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/30607967/6d7f3e74-6c5e-4962-8471-56da5046b4c0">

It seems that there is no support for storybook?
Any help would be appreciated.
Thanks

### Reproduce link

As per details section.

### Reproduce Steps

As per details section.

**Comment by 9aoy** [comment]
![20240304-191236](https://github.com/web-infra-dev/modern.js/assets/22373761/c1ed1000-d6c0-4848-b670-a8acc1cdce1a)
Did you move down to reveal all choices?  modern.js supports some features and Storybook doesn't show up on the first page :joy: .

**Comment by martin-repta** [comment]
Testing it again, you are right! thanks!
