### ISSUE TITLE
[Feature]: Replace ESLint with Biome

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/modern.js#5506]
### What problem does this feature solve?

ESLint has obvious performance issues in large monorepos like modern.js.

We can use Biome as the linter to replace ESLint, which can reduce dependencies and improve the lint performance.

Ref:

- https://biomejs.dev/
- https://github.com/web-infra-dev/rspress/pull/702

### What does the proposed API look like?

1. Add Biome to the Modern.js repo and replace ESLint.
2. Consider adding Biome to the project templates of Modern.js App and Module.
3. If 1 and 2 are done, we can remove the `@modern-js/eslint-config` package and reduce the maintenance overhead.

**Comment by kirillbashtenko** [comment]
Hello @chenjiahan , I'm curious why not **oxclint** since it's already part of the ecosystem?

**Comment by chenjiahan** [comment]
@kirillbashtenko Both Biome and OXC can be used to speed up linting, Modern.js choose to use Biome because it can be used for **both linting and formatting**.

Here is a discussion for comparison:  https://github.com/biomejs/biome/discussions/1281

**Comment by kirillbashtenko** [comment]
Thank you, now it's clear!

**Comment by YanPes** [comment]
@chenjiahan thank you for opening the issue. Would love to use biome with modernjs for our code bases

**Comment by ScriptedAlchemy** [comment]
bumpinng

**Comment by YanPes** [comment]
@chenjiahan  Is it planned to have a dedicated set of "default" fields or will you use the standard biome "recommended" list as default?

**Comment by YanPes** [comment]
Thank you for this 🎉
