### ISSUE TITLE
[Bug]: config/public中的 png 资源在获取时损坏，内容被修改

### ISSUE THREAD

**Issue by Gk0Wk** [web-infra-dev/modern.js#5622]
### 版本信息

```sh
System:
    OS: macOS 13.6.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 291.74 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Edge: 120.0.2210.133
    Safari: 17.4.1
  npmPackages:
    @modern-js/app-tools: 2.48.4 => 2.48.4
    @modern-js/eslint-config: 2.48.4 => 2.48.4
    @modern-js/runtime: 2.48.4 => 2.48.4
    @modern-js/tsconfig: 2.48.4 => 2.48.4
```

### 问题详情

创建一个Web项目(pnpm, TS, Rspack)， 创建config/public路径，在其中添加一张 png 图片，这里用 ModernJS 的 logo 为例：
<img width="109" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/16955102/88547ac0-675e-4614-903c-e13bb788f315">
`pnpm run dev` 启动服务，通过 `http://localhost:8080/1.png` 尝试获取图片，但是损坏
<img width="627" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/16955102/df7a27a4-6297-4dc1-b1da-ccdd2d63ee20">
尝试直接下载，发现二者的大小不同
<img width="632" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/16955102/f171dd23-5dba-4590-a781-0d83b8de87fb">

### 复现链接

https://github.com/Gk0Wk/modernjs-publicpng-bug-demo

### 复现步骤

见问题详情

**Comment by zllkjc** [comment]
We have already fixed it. just update to the latest version~
