### ISSUE TITLE
[Bug]: 依赖安装丢失,版本错误

### ISSUE THREAD

**Issue by czfadmin** [web-infra-dev/modern.js#5660]
### Version

```sh
System:
  OS: Windows 11 10.0.22631
  CPU: (19) x64 12th Gen Intel(R) Core(TM) i7-12700H
  Memory: 17.59 GB / 31.69 GB
Browsers:
  Edge: Chromium (123.0.2420.97), ChromiumDev (123.0.2420.10)
  Internet Explorer: 11.0.22621.1
```

### Details

使用最新的项目创建方式,出现版本安装错误

![image](https://github.com/web-infra-dev/modern.js/assets/13393959/f279aae9-8c6c-44b5-8b86-763d1a63c1ae)

### Reproduce link

none

### Reproduce Steps

npx @modern-js/create@latest npm-module
- 请选择你想创建的工程类型 Npm 模块
- 请填写项目名称 npm-module
- 请选择开发语言 TS
- 请选择包管理工具 pnpm

**Comment by KyrieLii** [comment]
重试下，可能你创建时刚好版本还没发完
这个版本存在的：https://www.npmjs.com/package/@modern-js/plugin-lint?activeTab=versions

**Comment by czfadmin** [comment]
是的, 所以这个ISSUS可以关闭了, 不过感觉这个moderjs的脚手架的创建的项目时候的依赖同步不是很及时啊

**Comment by KyrieLii** [comment]
这个问题偶然性太高，因为 modern.js 是保持版本号统一的，创建时的版本号是根据 soutions 来获取的（module-tools)。
能出现这个 case 只有：module-tools 2.49.0 发完了，plugin-lint 还没发，大概间隔几分钟，整体发布流程在10分钟以内。
如果每个包都确保版本存在，会让创建时间变长（每个包都 npm view 一下获取版本）
感觉不是很必要 😂

**Comment by KyrieLii** [comment]
当然也会有一些其他因素，比如没有用 npm registry，用了淘宝镜像中间有个同步延迟

**Comment by czfadmin** [comment]
理解的, 我昨晚用的就是淘宝镜像,可能是这个原因导致的 哈哈哈哈😂
