### ISSUE TITLE
部署的时候使用pm2来启动内置的Web 服务器，不支持pm2的Cluster模式

### ISSUE THREAD

**Issue by htscwgs** [web-infra-dev/modern.js#567]
### 版本信息

```sh
无
```

### 问题详情

新建一个 sh 文件，执行 npm run start，然后 pm2 启动这个 sh 文件，启动命令：pm2 start bootstrap.sh -i 4，启动之后的服务都是fork模式

### 问题复现

无

**Comment by chenjiahan** [comment]
This issue is being closed as it is out of date, please create a new issue if the problem still exists.
