### ISSUE TITLE
[Bug]: @modern-js/module-tools 输出 cjs 时 转换了 await import

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/modern.js#5795]
### 版本信息

```sh
System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 19.54 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 125.0.6422.113
    Safari: 17.4.1
```

## cjs
![image](https://github.com/web-infra-dev/modern.js/assets/69964024/7e47c2ef-b500-4acf-b4b3-481815c8431b)
## esm
![image](https://github.com/web-infra-dev/modern.js/assets/69964024/f45c976e-f7e4-4ec8-90b2-311cef6d1504)

### 复现链接

none

### 复现步骤

none

**Comment by fi3ework** [comment]
@modern-js/module-tools 底层是 esbuild，所以这本质上是 esbuild 的行为。

举个[例子](https://esbuild.github.io/try/#YgAwLjIxLjQALS1mb3JtYXQ9Y2pzIC0tdGFyZ2V0PWNocm9tZTYwIABlAGVudHJ5LmpzAGV4cG9ydCBhc3luYyBmdW5jdGlvbiBhICgpIHsKdHJ5IHsKICBpbXBvcnQoJy4vb3BlbicpCn0gY2F0Y2goZSkge30KCn0)，如果你的目标环境不支持 `import()`，esbuild 会自动将你源码中的 `import()` 转换为 `require`，是符合预期的行为。

如果你希望强制保留 `import()`，可以使用 https://esbuild.github.io/api/#supported （[demo](https://esbuild.github.io/try/#YgAwLjIxLjQALS1mb3JtYXQ9Y2pzIC0tdGFyZ2V0PWNocm9tZTYwIC0tc3VwcG9ydGVkOmR5bmFtaWMtaW1wb3J0PXRydWUAZQBlbnRyeS5qcwBleHBvcnQgYXN5bmMgZnVuY3Rpb24gYSAoKSB7CnRyeSB7CiAgaW1wb3J0KCcuL29wZW4nKQp9IGNhdGNoKGUpIHt9Cgp9)），修改 @modern-js/module-tools 配置文件中的 https://modernjs.dev/module-tools/api/config/build-config.html#esbuildoptions 即可。

如果有更多的问题，请提供复现链接及复现步骤帮助我们更好得排查（[「请提供最小重现」](https://antfu.me/posts/why-reproductions-are-required-zh)）。

**Comment by dingff** [comment]
https://github.com/web-infra-dev/modern.js/blob/b52060924b4ddb7ea5db109097ca723a9175e7b7/packages/solutions/module-tools/src/builder/esbuild/index.ts#L207
请问这里为什么要这样做呀？

**Comment by dingff** [comment]
@fi3ework

**Comment by fi3ework** [comment]
你指的是前面的还是后面的判断条件

**Comment by dingff** [comment]
> 你指的是前面的还是后面的判断条件

cjs为什么要关闭dynamic-import?

**Comment by dingff** [comment]
@fi3ework

**Comment by fi3ework** [comment]
因为 CJS 在低版本 node 的兼容性更好，而且 Node 对 code splitting 没有什么强的诉求

**Comment by dingff** [comment]
> 因为 CJS 在低版本 node 的兼容性更好，而且 Node 对 code splitting 没有什么强的诉求

但是这样在format为cjs时，动态导入的esm依赖就会报错，因为import被转换成了require，这个问题怎么解呢 @fi3ework

**Comment by fi3ework** [comment]
我最开始的回复已经回答了这个问题。

**Comment by dingff** [comment]
> 我最开始的回复已经回答了这个问题。

好的，感谢耐心解答
