### ISSUE TITLE
[Bug]: Unable to create monorepo with @modern-js/create

### ISSUE THREAD

**Issue by yf-yang** [web-infra-dev/modern.js#5823]
### Version

```sh
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.64 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
Browsers:
    Chrome: 125.0.6422.144
    Safari: 16.3

@modern-js/create v2.53.0
```

### Details

When using `{"solution": "monorepo"}` option [doc](https://modernjs.dev/en/guides/topic-detail/generator/create/config.html#solution)

``` shell
[ERROR] solution is not valid 
🚶  Load Generator...[WARN] load sub generator failed
```

I guess the cli has not yet supported it. Is there any workaround to directly use the monorepo-generator?

### Reproduce link

Nope

### Reproduce Steps

``` shell
pnpm create @modern-js -c '{"solution": "monorepo"}' modern
```

**Comment by yf-yang** [comment]
Hmmm seems the feature is just removed
https://github.com/web-infra-dev/modern.js/pull/5804

@caohuilin Would you please give me a link to the "community solution", thank you!

**Comment by zllkjc** [comment]
Hey, we no longer support creating Monorepo for Modern.js and recommend using the community's Monorepo tool directly like rush、nx and maybe juest pnpm-workspaces...

**Comment by yf-yang** [comment]
Sure, do you have any starter example repo?

**Comment by zllkjc** [comment]
Maybe you can see https://nx.dev/getting-started/intro

**Comment by yf-yang** [comment]
Sorry, I am not just asking for a monorepo. Is there a modern-js monorepo example with the configuration already set that I can start with?

**Comment by zllkjc** [comment]
Get, we don't have it now, you can first create an monorepo, and run `npx @modern-js/create` in a directory of monorepo where you want start your project

**Comment by yf-yang** [comment]
Fine, I'll try to follow the doc to make one.

**Comment by yf-yang** [comment]
That would be better if you can offer more examples like module federation does. Not sure if that's aligned with your okr 🤣
