### ISSUE TITLE
[Bug]: 项目启动时间过久

### ISSUE THREAD

**Issue by urielvan** [web-infra-dev/modern.js#5829]
### 版本信息

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 4.14 GB / 15.64 GB
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @modern-js/app-tools: 2.53.0 => 2.53.0 
    @modern-js/eslint-config: 2.53.0 => 2.53.0
    @modern-js/runtime: 2.53.0 => 2.53.0
    @modern-js/tsconfig: 2.53.0 => 2.53.0
```

### 问题详情

`npm start` 启动之后虽然很快就显示编译完成，但是实际浏览器中依然要等很久才能实际看到内容。

![image](https://github.com/web-infra-dev/modern.js/assets/14124339/d9bab102-3344-4625-a223-6de33cf34bb9)
如图编译只耗时了3秒左右
![image](https://github.com/web-infra-dev/modern.js/assets/14124339/6c2c27f1-941b-400f-97d5-ba27a454e5ae)
但是实际需要等上半分多钟才能看到，并且由于链接中仅是一个最小复现，实际项目中随着文件数量增加，目前需要等待的时间已经达到了2到3分钟

### 复现链接

https://github.com/urielvan/modern-js-example

### 复现步骤

执行 `npm start`，在显示链接后打开浏览器查看

**Comment by zllkjc** [comment]
这看起来像是个是网络问题。

**Comment by urielvan** [comment]
> 这看起来像是个是网络问题。

![image](https://github.com/web-infra-dev/modern.js/assets/14124339/9cffb79d-b115-4a97-9f2c-e95fda7ae1c6)
@zllkjc 我觉得不是网络问题，如图所示，就第一次请求特别耗时，后续再怎么刷新都能很流畅地加载完成
