### ISSUE TITLE
[Bug]: Missing I18n plugin

### ISSUE THREAD

**Issue by roonie007** [web-infra-dev/modern.js#5847]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 17.58 GB / 27.30 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    @modern-js/app-tools: 2.53.0 => 2.53.0 
    @modern-js/eslint-config: 2.53.0 => 2.53.0 
    @modern-js/plugin-bff: 2.53.0 => 2.53.0 
    @modern-js/plugin-express: 2.53.0 => 2.53.0 
    @modern-js/plugin-tailwindcss: 2.53.0 => 2.53.0 
    @modern-js/runtime: 2.53.0 => 2.53.0 
    @modern-js/tsconfig: 2.53.0 => 2.53.0
```

### Details

Missing i18n plugin in the `modern new` -> `Enable Features`

Also it looks like the modernjs documentation is missing the i18n plugin documentation section. 

### Reproduce link

No demo needed

### Reproduce Steps

Simply start any modern project and try to add a plugin using the `modern new`

**Comment by caohuilin** [comment]
What kind of ability do you need for i18n? Currently, the i18n plugin in Modern.js is only used internally.

**Comment by roonie007** [comment]
Well instead of installing a bunch of modules and setting up an i18n library, using your plugin would be a lot easier, and actually I am using it, and it works perfectly.

I installed it without using the CLI.

**Comment by joselrodrigues** [comment]
Hi @caohuilin, at work we are planning to migrate to Modern.js soon and we rely heavily on i18n. I've searched the documentation for any reference to an internal i18n plugin but haven't found any details. Could you please point me to any official guidance or documentation on how to configure i18n using Modern.js's internal i18n plugin, if available?

**Comment by caohuilin** [comment]
Modern.js doesn't provide built-in i18n plugin integration, but you can easily implement it using **i18next** and **react-i18next**. Here's a step-by-step solution:

---

## 1. Install Dependencies
```bash
pnpm add i18next react-i18next
```

## 2. Enable Custom Entry

Create `src/entry.tsx` with:

```ts
import { createRoot } from '@modern-js/runtime/react';
import { render } from '@modern-js/runtime/browser';

const ModernRoot = createRoot();
render(<ModernRoot />);
```

Update Configuration:
```ts
import { appTools, defineConfig } from '@modern-js/app-tools';

export default defineConfig({
  source: {
    enableCustomEntry: true,
  },
  // ... other config
});
```
## 3. Initialize i18n

Create `src/i18n.ts`:

```ts
import { createInstance } from 'i18next';
import { initReactI18next } from 'react-i18next';

const initOptions = {
  lng: 'en',
  ns: ['common', 'translation'],
  defaultNS: 'common',
  fallbackLng: ['en'],
  supportedLngs: ['en', 'zh'],
  resources: {
    en: {
      common: { hello_world: 'hello world' },
      translation: { hello: 'hello world' }
    },
    zh: {
      common: { hello_world: '你好世界' },
      translation: { hello: '你好，世界' }
    }
  }
};

// Using separate instance avoids potential conflicts
export const i18n = createInstance();

export function initI18nInstance() {
  return i18n.use(initReactI18next).init(initOptions);
}

```

Update `entry.tsx`:

```ts
import { createRoot } from '@modern-js/runtime/react';
import { render } from '@modern-js/runtime/browser';
import { initI18nInstance } from './i18n';

const ModernRoot = createRoot();

initI18nInstance().then(() => {
  render(<ModernRoot />);
});

```

## 4. Usage in Components
```ts
// src/routes/page.tsx
import { useTranslation } from 'react-i18next';
import { i18n } from '../i18n';

// Direct instance usage
const getText = () => i18n.t('translation:hello');

const Index = () => {
  const text = getText();
  const { t } = useTranslation();
  
  return (
    <>
      <p>{t('hello_world')}</p>
      <p>{text}</p>
    </>
  );
};

export default Index;

```

**Comment by joselrodrigues** [comment]
Thank you so much @caohuilin it works like a charm!
