### ISSUE TITLE
[Bug]: Project generator Link broken

### ISSUE THREAD

**Issue by raolak** [web-infra-dev/modern.js#5850]
### Version

```sh
System: MacOs
browser : Chrome
```

### Details

 Project generator Link  - (https://modernjs.dev/en/guides/topic-detail/generator/project) is broken, It would be great if we can fix this. 

### Reproduce link

NA

### Reproduce Steps

- Go to https://modernjs.dev/en/
- Click on [Project Generator] under Topics

**Comment by caohuilin** [comment]
https://modernjs.dev/en/guides/topic-detail/generator/create/use.html
