### ISSUE TITLE
[Feature]: Plugin for shadcn/ui

### ISSUE THREAD

**Issue by raolak** [web-infra-dev/modern.js#5851]
### What problem does this feature solve?

shadcn/ui is a popular Design system and providers out of the box components,.  It would be great if we can add 
shadcn-ui@latest init   support which can provides tooling for initial setup and managing components

### What does the proposed API look like?

support shadcn-ui@latest init

**Comment by yf-yang** [comment]
Why not directly add it as a dependency? shadcn doesn't involve any compile time stuff, so I suspect if it should be added. BTW I am currently using it with modern.js fluently.

**Comment by raolak** [comment]
Hi Yang

This is sorted.! It's working for me.  I can have a document for this.

_lnr

**Comment by raolak** [comment]
Also

In with pnpm run dev , I am able to module federation working. But I am not
sure how to get it working for production setup. I am planning to
containerise and deploy in k8s.

Any documentation or help is really appreciated !

Thank you
lnr

**Comment by zllkjc** [comment]
I will add some docs for module federation in modern.js website. now you can refer to module federation website to get some info
