### ISSUE TITLE
[Bug]: getAppList for micro-frontends now working anymore 

### ISSUE THREAD

**Issue by kirillbashtenko** [web-infra-dev/modern.js#5981]
### Version

```sh
System:
    OS: macOS 13.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 89.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.4.1
  npmPackages:
    @modern-js/app-tools: 2.55.0 => 2.55.0 
    @modern-js/eslint-config: 2.55.0 => 2.55.0 
    @modern-js/plugin-garfish: 2.55.0 => 2.55.0 
    @modern-js/runtime: 2.55.0 => 2.55.0 
    @modern-js/tsconfig: 2.55.0 => 2.55.0
```

### Details

Hi, since **2.55.0**  the **getAppList** is not executed anymore and it breaks current micro-frontends functionality.
Can you please take a look? Thank you

### Reproduce link

https://github.com/kirillbashtenko/modern-js-example

### Reproduce Steps

1 pnpm install &&  pnpm start
2 cd dashboard && pnpm install && pnpm start
3 cd table && pnpm install && pnpm start

**Comment by caohuilin** [comment]
The table and dashboard application should incorporate the @modern-js/plugin-garfish dependency.

The getAppList not working problem is already fixed. You can use this version for today's publish (1.58.1)

**Comment by kirillbashtenko** [comment]
@caohuilin thank you! all works on 2.58.2! just tested!
