### ISSUE TITLE
[Bug]: can not access app via ipv4

### ISSUE THREAD

**Issue by 2heal1** [web-infra-dev/modern.js#5999]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.41 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
  npmPackages:
    @modern-js/app-tools: 2.56.2 => 2.56.2 
    @modern-js/eslint-config: 2.56.2 => 2.56.2 
    @modern-js/runtime: 2.56.2 => 2.56.2 
    @modern-js/tsconfig: 2.56.2 => 2.56.2
```

### Details

can not visit via ipv4 , but can visit via localhost
![image](https://github.com/user-attachments/assets/5837bb5e-5c43-420d-9368-dbd52f32e3d9)

### Reproduce link

https://github.com/2heal1/modernjs-demo

### Reproduce Steps

* pnpm i 
* pnpm start

**Comment by 2heal1** [comment]
it can be solved by set `dev.host` as `0.0.0.0`

**Comment by GiveMe-A-Name** [comment]
cc https://github.com/web-infra-dev/modern.js @yimingjfe
