### ISSUE TITLE
[Feature]: 可选的集成支持以及外部模板

### ISSUE THREAD

**Issue by lanmingle** [web-infra-dev/modern.js#6065]
### 这个功能解决了什么问题？

对于 cli 工具，创建 lib 或 web 时
- .prettierrc
- .nvmrc
- .eslintrc.js
- .vscode
- .husky
- .changeset
能不能把这些变成可选的？
虽然可以手动删除，但是想要一个最简单最干净的工程是基于CLI创建的。

另外，对于默认模板是否可以提供可以通过外部的URL创建？
如：https://nextjs.org/docs/app/api-reference/create-next-app

```bash
 
  -e, --example [name]|[github-url]
 
    An example to bootstrap the app with. You can use an example name
    from the official Next.js repo or a public GitHub URL. The URL can use
    any branch and/or subdirectory
 
  --example-path <path-to-example>
 
    In a rare case, your GitHub URL might contain a branch name with
    a slash (e.g. bug/fix-1) and the path to the example (e.g. foo/bar).
    In this case, you must specify the path to the example separately:
    --example-path foo/bar
```

### 你期望的 API 是什么样子的？

--vscode boolean
--husky boolean
等等可选配置

**Comment by zllkjc** [comment]
这里有部分配置后续是会移除的，目前暂时不考虑在默认的 create 工具里提供一个完全干净的项目。
也许可以通过自定义模板的方式来创建，Modern.js 有自己的外部模板创建能力，现在暂时将文档下线了，后续梳理 API 后重新开放使用。

**Comment by lanmingle** [comment]
已解决
