### ISSUE TITLE
[Bug]: When building using useContext in koa I am getting a typing error

### ISSUE THREAD

**Issue by alexandesigner** [web-infra-dev/modern.js#6139]
### 版本信息

```sh
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 353.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.85
    Safari: 17.6
  npmPackages:
    @modern-js/app-tools: 2.58.1 => 2.58.1
    @modern-js/plugin-bff: 2.58.1 => 2.58.1
    @modern-js/plugin-garfish: 2.58.1 => 2.58.1
    @modern-js/plugin-koa: 2.58.1 => 2.58.1
    @modern-js/plugin-server: 2.58.1 => 2.58.1
    @modern-js/plugin-ssg: 2.58.1 => 2.58.1
    @modern-js/runtime: 2.58.1 => 2.58.1
    @modern-js/tsconfig: 2.58.1 => 2.58.1
```

### 问题详情

When building using useContext in koa I am getting a typing error

### 复现链接

No need

### 复现步骤

It works fine when developing, however when I build the application it appears that some export type is missing.

<img width="437" alt="Screenshot 2024-08-28 at 13 24 08" src="https://github.com/user-attachments/assets/3c128643-8396-482c-8b3d-eea22f93f06b">

<img width="1057" alt="Screenshot 2024-08-28 at 09 27 19" src="https://github.com/user-attachments/assets/f24c00d6-cb8b-4221-92dc-ac978e0241a3">

**Comment by yimingjfe** [comment]
I created a new project and run `build` command, but it didn't reproduce the issue, please provide a link to this project reproduction
