### ISSUE TITLE
[Bug]: 自定义 entry.tsx 时无法构建

### ISSUE THREAD

**Issue by lanmingle** [web-infra-dev/modern.js#6200]
### 版本信息

```sh
2.59.0

windows 10 （已测试mac和liunx没有问题）
```

### 问题详情

entry.tsx
``` tsx
import { createRoot } from '@modern-js/runtime/react';
import { render } from '@modern-js/runtime/browser';

const ModernRoot = createRoot();

async function beforeRender() {
  console.log('beforeRender');
}

beforeRender().then(() => {
  render(<ModernRoot />);
});
```

报错：Module not found: Error: Can't resolve '@_modern_js_srcentry.tsx' in 路径\node_modules\.modern-js\main

编译出来的 index.jsx
```jsx
import '@modern-js/runtime/registry/main';
  import '@_modern_js_src\entry.tsx'
export * from '@_modern_js_src\entry.tsx'
```

手动修改  路径\node_modules\.modern-js\main\index.jsx
```jsx
import '@modern-js/runtime/registry/main';
  import '@_modern_js_src/entry.tsx'
export * from '@_modern_js_src/entry.tsx'
```

### 复现链接

暂无

### 复现步骤

不论是 webpack 还是 rspack 都一样

**Comment by zllkjc** [comment]
看起来是拼路径的问题 @caohuilin ，有空可以看看~

**Comment by caohuilin** [comment]
> 看起来是拼路径的问题 @caohuilin ，有空可以看看~

好的

**Comment by caohuilin** [comment]
https://github.com/web-infra-dev/modern.js/pull/6205

**Comment by caohuilin** [comment]
@lanmingle This bug has been fixed. You can use the nightly version `"@modern-js/plugin-garfish":"0.0.0-nightly-20240910170704"` first. We will publish on Thursday.

**Comment by lanmingle** [comment]
@caohuilin 额。。。这个我在测试的时候，没有使用 garfish 相关，基于生成器生成一个项目，直接添加 entry.tsx 就出现上述的问题。

**Comment by caohuilin** [comment]
@lanmingle 如果没有使用 garfish 插件，生成的内容是不应该存在 export * from '@_modern_js_src/entry.tsx' 的，你再 check 一下看看
