### ISSUE TITLE
[Bug]: source maps doesn't work (rsbuild bug)

### ISSUE THREAD

**Issue by GiancarlosIO** [web-infra-dev/modern.js#6289]
### Details

I think it would be good to have an issue to track this bug related to the source map generation in production mode.

This bug has already been reported in rsbuild:

https://github.com/web-infra-dev/rsbuild/issues/3447

I have created this because the bug is also affecting the modern.js build.

**Comment by zllkjc** [comment]
I see it was already fixed in rsbuild, i will close the issue.

**Comment by GiancarlosIO** [comment]
hi @zllkjc yes!
but it's not already fixed in modernjs 🤔 . I think we would need to upgrade the rspack or rsbuild package in the modernjs dependencies to finally fix the source map issue 😢

**Comment by GiancarlosIO** [comment]
I can see this MR: https://github.com/web-infra-dev/modern.js/pull/6286 🎉 

How can I upgrade rsbuild by myself? maybe configuring `pnpm.overrides` or I need to install rsbuild manually in my project? 🤔
