### ISSUE TITLE
[Feature]: Examples 能否提供一个模块联邦应用级别模块的部署示例？

### ISSUE THREAD

**Issue by givingwu** [web-infra-dev/modern.js#6378]
### 这个功能解决了什么问题？

能否提供一个 模块联邦 [应用级别模块](https://modernjs.dev/guides/topic-detail/module-federation/application.html) 的部署示例？

### 你期望的 API 是什么样子的？

无API，文档需求

**Comment by zllkjc** [comment]
好的，我会在近期提供一个部署的示例。但是这里实际上和普通的 MF 部署没有太大的差异，只需要将 MF 部署到某个服务或 CDN 上即可在项目中使用。

**Comment by givingwu** [comment]
谢谢

**Comment by givingwu** [comment]
根据 [ISSUE#6339](https://github.com/web-infra-dev/modern.js/issues/6339#issuecomment-2413044975) 所言，这个 [应用级别模块](https://modernjs.dev/guides/topic-detail/module-federation/application.html) 的 DEMO 部署是否要分别提供 CSR 跟 SSR 版本？

**Comment by zllkjc** [comment]
目前应用级别模块无法在 SSR 的时候使用哈。

**Comment by givingwu** [comment]
我只需要 CSR 场景，看起来是支持的，感谢回复。
