### ISSUE TITLE
[Bug]: 模块联邦host dev运行无法下载remote的@mf-types到本地

### ISSUE THREAD

**Issue by tky753** [web-infra-dev/modern.js#6393]
### 版本信息

System:
    OS: Windows 11 10.0.22631
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 13.99 GB / 31.95 GB
Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
npmPackages:
    @modern-js/app-tools: 2.60.3 => 2.60.3 
    @modern-js/module-tools: 2.60.3 => 2.60.3 
    @modern-js/runtime: 2.60.3 => 2.60.3

### 问题详情

参照[文档](https://modernjs.dev/guides/topic-detail/module-federation/usage.html#%E6%B6%88%E8%B4%B9%E8%80%85%E4%BD%BF%E7%94%A8%E6%A8%A1%E5%9D%97)
host在dev时应该会自动下载remotes的@mf-types才对。
我之前用rsbuild+MF2的时候也确实会自动下载。
但现在转到modern.js后就不行了，试了实例项目，发现也不行。
我看 http://localhost:xxxx/mf-manifest.json 中明明是有metaData.types节点的，
调用 http://localhost:xxxx/@mf-types.zip  也确实能下载到内容

### 复现链接

https://github.com/web-infra-dev/modern-js-examples/tree/main/examples/module-federation/base

### 复现步骤

console1:
cd module-federation\base\remote
pnpm i
pnpm dev

console2:
cd module-federation\base\host
pnpm i
rm -rf @mf-types
pnpm dev

浏览器打开http://localhost:8080，console2 出现错误
![Image](https://github.com/user-attachments/assets/fbafa980-2a8d-490c-abcf-f16c08f42d9d)

**Comment by tky753** [comment]
有个同事电脑可以，我试了就不行，应该是我哪里配置有问题，我再看看吧。

**Comment by tky753** [comment]
应该不是modern.js的问题，我试了rsbuild的例子，也无法下载。把node升级到了最新，还尝试了yarn，还是不行。
不知道是不是系统的问题。
下一步要试的话，得要调试mf源码了，算了，懒得折腾了

**Comment by zllkjc** [comment]
有可能是你全局 ts 版本，或者上层目录 tsconfig.json 的问题等。
