### ISSUE TITLE
[Feature]: Modern.js Module build support module federation

### ISSUE THREAD

**Issue by tky753** [web-infra-dev/modern.js#6401]
### 这个功能解决了什么问题？

开发插件架构项目。
1. 主项目相当于一个基座，用`Modern.js framework`开发打包；
2. 功能模块放在nginx里用**模块联邦**动态加载。

### 你期望的 API 是什么样子的？

Modern.js Module 打包支持 模块联邦

**Comment by nyqykk** [comment]
是说希望 provider 是 module 类型吗

**Comment by tky753** [comment]
modern.config.ts 类似于这样：
```ts
import { defineConfig, moduleTools } from '@modern-js/module-tools'
import { moduleFederationPlugin } from '@module-federation/modern-js'

export default defineConfig({
  plugins: [moduleTools(), moduleFederationPlugin()],
  buildConfig: {
    ...
  }
})

```

**Comment by tky753** [comment]
这个rslib感觉和modern.js module是不是定位冲突了?

**Comment by nyqykk** [comment]
> 这个rslib感觉和modern.js module是不是定位重叠了?

不一样，modern module 是 esbuild 构建，rslib 是 rspack 构建，后续会比较推荐 rslib
