### ISSUE TITLE
[Bug]: @modern-js/create 不再支持创建npm包了？

### ISSUE THREAD

**Issue by wangjue666** [web-infra-dev/modern.js#6531]
### Version

```sh
npx @modern-js/create create-multi-chrome
? 请选择开发语言 TS
? 请选择包管理工具 pnpm
```

### Details

https://modernjs.dev/module-tools/guide/intro/getting-started.html 文档上也没有任何下线的说明？

### Reproduce link

暂无

### Reproduce Steps

直接创建即可

**Comment by caohuilin** [comment]
推荐使用 rslib 了，@chenjiahan 来个 rslib 的文档呗

**Comment by chenjiahan** [comment]
Sorry https://modernjs.dev/module-tools/guide/intro/getting-started.html 的内容还未更新，我们会在今天处理

- 本次调整的背景在这个 PR 中有描述：https://github.com/web-infra-dev/modern.js/pull/6491
- 推荐用的 Rslib 仓库：https://github.com/web-infra-dev/rslib
- 文档：https://lib.rsbuild.dev/

**Comment by wangjue666** [comment]
了解了 感谢！
