### ISSUE TITLE
[Bug]: 升级报错import_plugin_i18n.I18n is not a constructor

### ISSUE THREAD

**Issue by lhx15** [web-infra-dev/modern.js#6550]
### 版本信息

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 3.51 GB / 15.69 GB
  Browsers:
    Edge: Chromium (127.0.2651.86)
```

### 问题详情

![Image](https://github.com/user-attachments/assets/8d80956b-4f71-4900-a850-e7e6742cee38)
npm run upgrade

> newModerm@0.1.0 upgrade
> modern upgrade

  Modern.js Framework v2.59.0

🚶  Load Generator...[ERROR] run task error: TypeError: import_plugin_i18n.I18n is not a constructor

### 复现链接

无

### 复现步骤

v2.59.0 执行npm run upgrade

**Comment by caohuilin** [comment]
https://github.com/web-infra-dev/modern.js/pull/6551
