### ISSUE TITLE
[Feature]: 支持同时使用 约定式路由 和 运行时配置

### ISSUE THREAD

**Issue by tky753** [web-infra-dev/modern.js#6602]
### What problem does this feature solve?

我的项目是基于模块联邦的，路由是从各个remote那里运行时加载过来的，所以必须要用**路由运行时配置**。
现在用了 [运行时配置](https://modernjs.dev/guides/basic-features/routes.html#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)的话，**routes/layout.ts**下的 `export default () => {...}` 会失效，可能是因为这部分是**约定式路由**才会用到。
那我就不知道应该在哪里写全局`Context.Provider`了。

### What does the proposed API look like?

能否给**运行时配置**加一个 `updateRoutes(参数：约定式路由生成的路由)`的方法，使得用户可以同时在**约定式路由**的基础之上运行时添加自定义路由或者修改自动生成的路由。

**Comment by caohuilin** [comment]
@tky753 可以来个 example 吗？

**Comment by tky753** [comment]
@caohuilin  代码示例：

routes/layout.ts
```ts
import type { AppConfig, RouterConfig } from '@modern-js/runtime'
import { Outlet, type RouteObject } from '@modern-js/runtime/router'

export const config = (): AppConfig => {
  return {
    router: {
      createRoutes() {
        return [
          ...
        ] as RouteObject[]
      }
    } as RouterConfig
  }
}

// 以下代码失效
export default () => {
  return (
    <>
      <CustomRootProviders>
        <Outlet></Outlet>
      </CustomRootProviders>
    </>
  )
}
```

**Comment by caohuilin** [comment]
@tky753  CustomRootProviders 没生效？这个里面是什么逻辑呀？

**Comment by tky753** [comment]
@caohuilin  我看modern.js代码，约定式路由和 运行时配置就是互斥的吧，下面那部分属于约定式路由，如果上面配置了createRoutes就不会走到下面的代码了
![Image](https://github.com/user-attachments/assets/10da31ed-a546-4f39-82b5-c2714b14a738)

**Comment by caohuilin** [comment]
@tky753 是的，createRoutes 参数是这个逻辑，感觉你的需求可以在 modifyRoutes 中实现

**Comment by caohuilin** [comment]
在 `src/modern.runtime.tsx` 中自定义一个 runtime 插件，然后在里面补充一个自己的 router
```
import { type Plugin, defineRuntimeConfig } from '@modern-js/runtime';
import type { RouteObject } from '@modern-js/runtime/router';
import React from 'react';

const routerCustomPlugin = () =>
  ({
    name: 'router-custom-plugin',
    setup: () => {
      return {
        modifyRoutes: (routes: RouteObject[]) => {
          routes.push({
            path: '/test',
            element: <div>test</div>,
          });
          return routes;
        },
      };
    },
  }) as Plugin;
export default defineRuntimeConfig({
  plugins: [routerCustomPlugin()],
});

```

**Comment by tky753** [comment]
@caohuilin 这个好，感觉比**运行时配置**要实用多了，建议在路由那一页的文档里添加一下这个。

**Comment by caohuilin** [comment]
@tky753 嗯，运行时插件现在还没有正式对外，稳定了之后，会添加这里的文档的

**Comment by tky753** [comment]
@caohuilin 我试了一下，发现用modifyRoutes虽然可以在 约定式路由 封装好的路由的基础上添加其他路由。 
但后添加的路由和通过 `createRoutes`创建的路由一样，走不到
```ts
export default () => {
  return (
    <>
      <CustomRootProviders>
        <Outlet></Outlet>
      </CustomRootProviders>
    </>
  )
}
```
这段代码。

因为这个root layout代码**只能通过约定式路由封装才能生效**。

**Comment by caohuilin** [comment]
有的，也在刚刚那个自定义插件用 wrapRoot hook 实现

**Comment by tky753** [comment]
@caohuilin  我发现了，不过我发现我的provider必须在router的provider里面，这个plugin的加载顺序有办法控制吗？

**Comment by caohuilin** [comment]
在 modifyRoutes 里面的 routes 里面加一下 layout 字段应该就能跑到了

**Comment by tky753** [comment]
成了，感谢：
routes/layout.tsx
```ts
export default () => {
  return (
    <>
      <CustomRootProviders>
        <Outlet></Outlet>
      </CustomRootProviders>
    </>
  )
}
```

modern.runtime.ts
```ts

const runtimeRoutePlugin: Plugin = {
  name: 'runtime-route-plugin',
  setup: () => {
    return {
      modifyRoutes: (routes: RouteObject[]) => {
        routes[0].children!.push(...getCustomRoutes())
      }
    }
  }
} as Plugin

export default defineRuntimeConfig({
  plugins: [runtimeRoutePlugin]
})
```
